using Test
using Reseau

include("eventloops_tests.jl")
include("internal_poll_tests.jl")
include("socket_ops_tests.jl")
include("tcp_tests.jl")
include("host_resolvers_tests.jl")
include("tls_tests.jl")
include("http_core_tests.jl")
include("http1_wire_tests.jl")
include("http_client_transport_tests.jl")
include("http_client_tests.jl")
include("http_server_http1_tests.jl")
include("hpack_tests.jl")
include("http2_frame_tests.jl")
include("http2_client_tests.jl")
include("http2_server_tests.jl")
include("http_integration_tests.jl")
include("http_parity_tests.jl")
include("trim_compile_tests.jl")
