# AWS IO Library - Core definitions
# Port of aws-c-io/include/aws/io/io.h

const IO_PACKAGE_ID = 1

# Error codes for IO operations
const ERROR_IO_CHANNEL_ERROR_CANT_ACCEPT_INPUT = ERROR_ENUM_BEGIN_RANGE(IO_PACKAGE_ID)
const ERROR_IO_CHANNEL_UNKNOWN_MESSAGE_TYPE = ERROR_IO_CHANNEL_ERROR_CANT_ACCEPT_INPUT + 1
const ERROR_IO_CHANNEL_READ_WOULD_EXCEED_WINDOW = ERROR_IO_CHANNEL_UNKNOWN_MESSAGE_TYPE + 1
const ERROR_IO_EVENT_LOOP_ALREADY_ASSIGNED = ERROR_IO_CHANNEL_READ_WOULD_EXCEED_WINDOW + 1
const ERROR_IO_EVENT_LOOP_SHUTDOWN = ERROR_IO_EVENT_LOOP_ALREADY_ASSIGNED + 1
const ERROR_IO_TLS_ERROR_NEGOTIATION_FAILURE = ERROR_IO_EVENT_LOOP_SHUTDOWN + 1
const ERROR_IO_TLS_ERROR_NOT_NEGOTIATED = ERROR_IO_TLS_ERROR_NEGOTIATION_FAILURE + 1
const ERROR_IO_TLS_ERROR_WRITE_FAILURE = ERROR_IO_TLS_ERROR_NOT_NEGOTIATED + 1
const ERROR_IO_TLS_ERROR_ALERT_RECEIVED = ERROR_IO_TLS_ERROR_WRITE_FAILURE + 1
const ERROR_IO_TLS_CTX_ERROR = ERROR_IO_TLS_ERROR_ALERT_RECEIVED + 1
const ERROR_IO_TLS_VERSION_UNSUPPORTED = ERROR_IO_TLS_CTX_ERROR + 1
const ERROR_IO_TLS_CIPHER_PREF_UNSUPPORTED = ERROR_IO_TLS_VERSION_UNSUPPORTED + 1
const ERROR_IO_MISSING_ALPN_MESSAGE = ERROR_IO_TLS_CIPHER_PREF_UNSUPPORTED + 1
const ERROR_IO_UNHANDLED_ALPN_PROTOCOL_MESSAGE = ERROR_IO_MISSING_ALPN_MESSAGE + 1
const ERROR_IO_FILE_VALIDATION_FAILURE = ERROR_IO_UNHANDLED_ALPN_PROTOCOL_MESSAGE + 1
const ERROR_IO_EVENT_LOOP_THREAD_ONLY = ERROR_IO_FILE_VALIDATION_FAILURE + 1
const ERROR_IO_ALREADY_SUBSCRIBED = ERROR_IO_EVENT_LOOP_THREAD_ONLY + 1
const ERROR_IO_NOT_SUBSCRIBED = ERROR_IO_ALREADY_SUBSCRIBED + 1
const ERROR_IO_OPERATION_CANCELLED = ERROR_IO_NOT_SUBSCRIBED + 1
const ERROR_IO_READ_WOULD_BLOCK = ERROR_IO_OPERATION_CANCELLED + 1
const ERROR_IO_BROKEN_PIPE = ERROR_IO_READ_WOULD_BLOCK + 1
const ERROR_IO_SOCKET_UNSUPPORTED_ADDRESS_FAMILY = ERROR_IO_BROKEN_PIPE + 1
const ERROR_IO_SOCKET_INVALID_OPERATION_FOR_TYPE = ERROR_IO_SOCKET_UNSUPPORTED_ADDRESS_FAMILY + 1
const ERROR_IO_SOCKET_CONNECTION_REFUSED = ERROR_IO_SOCKET_INVALID_OPERATION_FOR_TYPE + 1
const ERROR_IO_SOCKET_TIMEOUT = ERROR_IO_SOCKET_CONNECTION_REFUSED + 1
const ERROR_IO_SOCKET_NO_ROUTE_TO_HOST = ERROR_IO_SOCKET_TIMEOUT + 1
const ERROR_IO_SOCKET_NETWORK_DOWN = ERROR_IO_SOCKET_NO_ROUTE_TO_HOST + 1
const ERROR_IO_SOCKET_CLOSED = ERROR_IO_SOCKET_NETWORK_DOWN + 1
const ERROR_IO_SOCKET_NOT_CONNECTED = ERROR_IO_SOCKET_CLOSED + 1
const ERROR_IO_SOCKET_INVALID_OPTIONS = ERROR_IO_SOCKET_NOT_CONNECTED + 1
const ERROR_IO_SOCKET_ADDRESS_IN_USE = ERROR_IO_SOCKET_INVALID_OPTIONS + 1
const ERROR_IO_SOCKET_INVALID_ADDRESS = ERROR_IO_SOCKET_ADDRESS_IN_USE + 1
const ERROR_IO_SOCKET_ILLEGAL_OPERATION_FOR_STATE = ERROR_IO_SOCKET_INVALID_ADDRESS + 1
const ERROR_IO_SOCKET_CONNECT_ABORTED = ERROR_IO_SOCKET_ILLEGAL_OPERATION_FOR_STATE + 1
const ERROR_IO_DNS_QUERY_FAILED = ERROR_IO_SOCKET_CONNECT_ABORTED + 1
const ERROR_IO_DNS_INVALID_NAME = ERROR_IO_DNS_QUERY_FAILED + 1
const ERROR_IO_DNS_NO_ADDRESS_FOR_HOST = ERROR_IO_DNS_INVALID_NAME + 1
const ERROR_IO_DNS_HOST_REMOVED_FROM_CACHE = ERROR_IO_DNS_NO_ADDRESS_FOR_HOST + 1
const ERROR_IO_STREAM_INVALID_SEEK_POSITION = ERROR_IO_DNS_HOST_REMOVED_FROM_CACHE + 1
const ERROR_IO_STREAM_READ_FAILED = ERROR_IO_STREAM_INVALID_SEEK_POSITION + 1
const ERROR_IO_INVALID_FILE_HANDLE_DEPRECATED = ERROR_IO_STREAM_READ_FAILED + 1
const ERROR_IO_SHARED_LIBRARY_LOAD_FAILURE = ERROR_IO_INVALID_FILE_HANDLE_DEPRECATED + 1
const ERROR_IO_SHARED_LIBRARY_FIND_SYMBOL_FAILURE = ERROR_IO_SHARED_LIBRARY_LOAD_FAILURE + 1
const ERROR_IO_TLS_NEGOTIATION_TIMEOUT = ERROR_IO_SHARED_LIBRARY_FIND_SYMBOL_FAILURE + 1
const ERROR_IO_TLS_ALERT_NOT_GRACEFUL = ERROR_IO_TLS_NEGOTIATION_TIMEOUT + 1
const ERROR_IO_MAX_RETRIES_EXCEEDED = ERROR_IO_TLS_ALERT_NOT_GRACEFUL + 1
const ERROR_IO_RETRY_PERMISSION_DENIED = ERROR_IO_MAX_RETRIES_EXCEEDED + 1
const ERROR_IO_TLS_DIGEST_ALGORITHM_UNSUPPORTED = ERROR_IO_RETRY_PERMISSION_DENIED + 1
const ERROR_IO_TLS_SIGNATURE_ALGORITHM_UNSUPPORTED = ERROR_IO_TLS_DIGEST_ALGORITHM_UNSUPPORTED + 1
const ERROR_IO_PKCS11_VERSION_UNSUPPORTED = ERROR_IO_TLS_SIGNATURE_ALGORITHM_UNSUPPORTED + 1
const ERROR_IO_PKCS11_TOKEN_NOT_FOUND = ERROR_IO_PKCS11_VERSION_UNSUPPORTED + 1
const ERROR_IO_PKCS11_KEY_NOT_FOUND = ERROR_IO_PKCS11_TOKEN_NOT_FOUND + 1
const ERROR_IO_PKCS11_KEY_TYPE_UNSUPPORTED = ERROR_IO_PKCS11_KEY_NOT_FOUND + 1
const ERROR_IO_PKCS11_UNKNOWN_CRYPTOKI_RETURN_VALUE = ERROR_IO_PKCS11_KEY_TYPE_UNSUPPORTED + 1
# PKCS#11 CKR_* error codes
const ERROR_IO_PKCS11_CKR_CANCEL = ERROR_IO_PKCS11_UNKNOWN_CRYPTOKI_RETURN_VALUE + 1
const ERROR_IO_PKCS11_CKR_HOST_MEMORY = ERROR_IO_PKCS11_CKR_CANCEL + 1
const ERROR_IO_PKCS11_CKR_SLOT_ID_INVALID = ERROR_IO_PKCS11_CKR_HOST_MEMORY + 1
const ERROR_IO_PKCS11_CKR_GENERAL_ERROR = ERROR_IO_PKCS11_CKR_SLOT_ID_INVALID + 1
const ERROR_IO_PKCS11_CKR_FUNCTION_FAILED = ERROR_IO_PKCS11_CKR_GENERAL_ERROR + 1
const ERROR_IO_PKCS11_CKR_ARGUMENTS_BAD = ERROR_IO_PKCS11_CKR_FUNCTION_FAILED + 1
const ERROR_IO_PKCS11_CKR_NO_EVENT = ERROR_IO_PKCS11_CKR_ARGUMENTS_BAD + 1
const ERROR_IO_PKCS11_CKR_NEED_TO_CREATE_THREADS = ERROR_IO_PKCS11_CKR_NO_EVENT + 1
const ERROR_IO_PKCS11_CKR_CANT_LOCK = ERROR_IO_PKCS11_CKR_NEED_TO_CREATE_THREADS + 1
const ERROR_IO_PKCS11_CKR_ATTRIBUTE_READ_ONLY = ERROR_IO_PKCS11_CKR_CANT_LOCK + 1
const ERROR_IO_PKCS11_CKR_ATTRIBUTE_SENSITIVE = ERROR_IO_PKCS11_CKR_ATTRIBUTE_READ_ONLY + 1
const ERROR_IO_PKCS11_CKR_ATTRIBUTE_TYPE_INVALID = ERROR_IO_PKCS11_CKR_ATTRIBUTE_SENSITIVE + 1
const ERROR_IO_PKCS11_CKR_ATTRIBUTE_VALUE_INVALID = ERROR_IO_PKCS11_CKR_ATTRIBUTE_TYPE_INVALID + 1
const ERROR_IO_PKCS11_CKR_ACTION_PROHIBITED = ERROR_IO_PKCS11_CKR_ATTRIBUTE_VALUE_INVALID + 1
const ERROR_IO_PKCS11_CKR_DATA_INVALID = ERROR_IO_PKCS11_CKR_ACTION_PROHIBITED + 1
const ERROR_IO_PKCS11_CKR_DATA_LEN_RANGE = ERROR_IO_PKCS11_CKR_DATA_INVALID + 1
const ERROR_IO_PKCS11_CKR_DEVICE_ERROR = ERROR_IO_PKCS11_CKR_DATA_LEN_RANGE + 1
const ERROR_IO_PKCS11_CKR_DEVICE_MEMORY = ERROR_IO_PKCS11_CKR_DEVICE_ERROR + 1
const ERROR_IO_PKCS11_CKR_DEVICE_REMOVED = ERROR_IO_PKCS11_CKR_DEVICE_MEMORY + 1
const ERROR_IO_PKCS11_CKR_ENCRYPTED_DATA_INVALID = ERROR_IO_PKCS11_CKR_DEVICE_REMOVED + 1
const ERROR_IO_PKCS11_CKR_ENCRYPTED_DATA_LEN_RANGE = ERROR_IO_PKCS11_CKR_ENCRYPTED_DATA_INVALID + 1
const ERROR_IO_PKCS11_CKR_FUNCTION_CANCELED = ERROR_IO_PKCS11_CKR_ENCRYPTED_DATA_LEN_RANGE + 1
const ERROR_IO_PKCS11_CKR_FUNCTION_NOT_PARALLEL = ERROR_IO_PKCS11_CKR_FUNCTION_CANCELED + 1
const ERROR_IO_PKCS11_CKR_FUNCTION_NOT_SUPPORTED = ERROR_IO_PKCS11_CKR_FUNCTION_NOT_PARALLEL + 1
const ERROR_IO_PKCS11_CKR_KEY_HANDLE_INVALID = ERROR_IO_PKCS11_CKR_FUNCTION_NOT_SUPPORTED + 1
const ERROR_IO_PKCS11_CKR_KEY_SIZE_RANGE = ERROR_IO_PKCS11_CKR_KEY_HANDLE_INVALID + 1
const ERROR_IO_PKCS11_CKR_KEY_TYPE_INCONSISTENT = ERROR_IO_PKCS11_CKR_KEY_SIZE_RANGE + 1
const ERROR_IO_PKCS11_CKR_KEY_NOT_NEEDED = ERROR_IO_PKCS11_CKR_KEY_TYPE_INCONSISTENT + 1
const ERROR_IO_PKCS11_CKR_KEY_CHANGED = ERROR_IO_PKCS11_CKR_KEY_NOT_NEEDED + 1
const ERROR_IO_PKCS11_CKR_KEY_NEEDED = ERROR_IO_PKCS11_CKR_KEY_CHANGED + 1
const ERROR_IO_PKCS11_CKR_KEY_INDIGESTIBLE = ERROR_IO_PKCS11_CKR_KEY_NEEDED + 1
const ERROR_IO_PKCS11_CKR_KEY_FUNCTION_NOT_PERMITTED = ERROR_IO_PKCS11_CKR_KEY_INDIGESTIBLE + 1
const ERROR_IO_PKCS11_CKR_KEY_NOT_WRAPPABLE = ERROR_IO_PKCS11_CKR_KEY_FUNCTION_NOT_PERMITTED + 1
const ERROR_IO_PKCS11_CKR_KEY_UNEXTRACTABLE = ERROR_IO_PKCS11_CKR_KEY_NOT_WRAPPABLE + 1
const ERROR_IO_PKCS11_CKR_MECHANISM_INVALID = ERROR_IO_PKCS11_CKR_KEY_UNEXTRACTABLE + 1
const ERROR_IO_PKCS11_CKR_MECHANISM_PARAM_INVALID = ERROR_IO_PKCS11_CKR_MECHANISM_INVALID + 1
const ERROR_IO_PKCS11_CKR_OBJECT_HANDLE_INVALID = ERROR_IO_PKCS11_CKR_MECHANISM_PARAM_INVALID + 1
const ERROR_IO_PKCS11_CKR_OPERATION_ACTIVE = ERROR_IO_PKCS11_CKR_OBJECT_HANDLE_INVALID + 1
const ERROR_IO_PKCS11_CKR_OPERATION_NOT_INITIALIZED = ERROR_IO_PKCS11_CKR_OPERATION_ACTIVE + 1
const ERROR_IO_PKCS11_CKR_PIN_INCORRECT = ERROR_IO_PKCS11_CKR_OPERATION_NOT_INITIALIZED + 1
const ERROR_IO_PKCS11_CKR_PIN_INVALID = ERROR_IO_PKCS11_CKR_PIN_INCORRECT + 1
const ERROR_IO_PKCS11_CKR_PIN_LEN_RANGE = ERROR_IO_PKCS11_CKR_PIN_INVALID + 1
const ERROR_IO_PKCS11_CKR_PIN_EXPIRED = ERROR_IO_PKCS11_CKR_PIN_LEN_RANGE + 1
const ERROR_IO_PKCS11_CKR_PIN_LOCKED = ERROR_IO_PKCS11_CKR_PIN_EXPIRED + 1
const ERROR_IO_PKCS11_CKR_SESSION_CLOSED = ERROR_IO_PKCS11_CKR_PIN_LOCKED + 1
const ERROR_IO_PKCS11_CKR_SESSION_COUNT = ERROR_IO_PKCS11_CKR_SESSION_CLOSED + 1
const ERROR_IO_PKCS11_CKR_SESSION_HANDLE_INVALID = ERROR_IO_PKCS11_CKR_SESSION_COUNT + 1
const ERROR_IO_PKCS11_CKR_SESSION_PARALLEL_NOT_SUPPORTED = ERROR_IO_PKCS11_CKR_SESSION_HANDLE_INVALID + 1
const ERROR_IO_PKCS11_CKR_SESSION_READ_ONLY = ERROR_IO_PKCS11_CKR_SESSION_PARALLEL_NOT_SUPPORTED + 1
const ERROR_IO_PKCS11_CKR_SESSION_EXISTS = ERROR_IO_PKCS11_CKR_SESSION_READ_ONLY + 1
const ERROR_IO_PKCS11_CKR_SESSION_READ_ONLY_EXISTS = ERROR_IO_PKCS11_CKR_SESSION_EXISTS + 1
const ERROR_IO_PKCS11_CKR_SESSION_READ_WRITE_SO_EXISTS = ERROR_IO_PKCS11_CKR_SESSION_READ_ONLY_EXISTS + 1
const ERROR_IO_PKCS11_CKR_SIGNATURE_INVALID = ERROR_IO_PKCS11_CKR_SESSION_READ_WRITE_SO_EXISTS + 1
const ERROR_IO_PKCS11_CKR_SIGNATURE_LEN_RANGE = ERROR_IO_PKCS11_CKR_SIGNATURE_INVALID + 1
const ERROR_IO_PKCS11_CKR_TEMPLATE_INCOMPLETE = ERROR_IO_PKCS11_CKR_SIGNATURE_LEN_RANGE + 1
const ERROR_IO_PKCS11_CKR_TEMPLATE_INCONSISTENT = ERROR_IO_PKCS11_CKR_TEMPLATE_INCOMPLETE + 1
const ERROR_IO_PKCS11_CKR_TOKEN_NOT_PRESENT = ERROR_IO_PKCS11_CKR_TEMPLATE_INCONSISTENT + 1
const ERROR_IO_PKCS11_CKR_TOKEN_NOT_RECOGNIZED = ERROR_IO_PKCS11_CKR_TOKEN_NOT_PRESENT + 1
const ERROR_IO_PKCS11_CKR_TOKEN_WRITE_PROTECTED = ERROR_IO_PKCS11_CKR_TOKEN_NOT_RECOGNIZED + 1
const ERROR_IO_PKCS11_CKR_UNWRAPPING_KEY_HANDLE_INVALID = ERROR_IO_PKCS11_CKR_TOKEN_WRITE_PROTECTED + 1
const ERROR_IO_PKCS11_CKR_UNWRAPPING_KEY_SIZE_RANGE = ERROR_IO_PKCS11_CKR_UNWRAPPING_KEY_HANDLE_INVALID + 1
const ERROR_IO_PKCS11_CKR_UNWRAPPING_KEY_TYPE_INCONSISTENT = ERROR_IO_PKCS11_CKR_UNWRAPPING_KEY_SIZE_RANGE + 1
const ERROR_IO_PKCS11_CKR_USER_ALREADY_LOGGED_IN = ERROR_IO_PKCS11_CKR_UNWRAPPING_KEY_TYPE_INCONSISTENT + 1
const ERROR_IO_PKCS11_CKR_USER_NOT_LOGGED_IN = ERROR_IO_PKCS11_CKR_USER_ALREADY_LOGGED_IN + 1
const ERROR_IO_PKCS11_CKR_USER_PIN_NOT_INITIALIZED = ERROR_IO_PKCS11_CKR_USER_NOT_LOGGED_IN + 1
const ERROR_IO_PKCS11_CKR_USER_TYPE_INVALID = ERROR_IO_PKCS11_CKR_USER_PIN_NOT_INITIALIZED + 1
const ERROR_IO_PKCS11_CKR_USER_ANOTHER_ALREADY_LOGGED_IN = ERROR_IO_PKCS11_CKR_USER_TYPE_INVALID + 1
const ERROR_IO_PKCS11_CKR_USER_TOO_MANY_TYPES = ERROR_IO_PKCS11_CKR_USER_ANOTHER_ALREADY_LOGGED_IN + 1
const ERROR_IO_PKCS11_CKR_WRAPPED_KEY_INVALID = ERROR_IO_PKCS11_CKR_USER_TOO_MANY_TYPES + 1
const ERROR_IO_PKCS11_CKR_WRAPPED_KEY_LEN_RANGE = ERROR_IO_PKCS11_CKR_WRAPPED_KEY_INVALID + 1
const ERROR_IO_PKCS11_CKR_WRAPPING_KEY_HANDLE_INVALID = ERROR_IO_PKCS11_CKR_WRAPPED_KEY_LEN_RANGE + 1
const ERROR_IO_PKCS11_CKR_WRAPPING_KEY_SIZE_RANGE = ERROR_IO_PKCS11_CKR_WRAPPING_KEY_HANDLE_INVALID + 1
const ERROR_IO_PKCS11_CKR_WRAPPING_KEY_TYPE_INCONSISTENT = ERROR_IO_PKCS11_CKR_WRAPPING_KEY_SIZE_RANGE + 1
const ERROR_IO_PKCS11_CKR_RANDOM_SEED_NOT_SUPPORTED = ERROR_IO_PKCS11_CKR_WRAPPING_KEY_TYPE_INCONSISTENT + 1
const ERROR_IO_PKCS11_CKR_RANDOM_NO_RNG = ERROR_IO_PKCS11_CKR_RANDOM_SEED_NOT_SUPPORTED + 1
const ERROR_IO_PKCS11_CKR_DOMAIN_PARAMS_INVALID = ERROR_IO_PKCS11_CKR_RANDOM_NO_RNG + 1
const ERROR_IO_PKCS11_CKR_CURVE_NOT_SUPPORTED = ERROR_IO_PKCS11_CKR_DOMAIN_PARAMS_INVALID + 1
const ERROR_IO_PKCS11_CKR_BUFFER_TOO_SMALL = ERROR_IO_PKCS11_CKR_CURVE_NOT_SUPPORTED + 1
const ERROR_IO_PKCS11_CKR_SAVED_STATE_INVALID = ERROR_IO_PKCS11_CKR_BUFFER_TOO_SMALL + 1
const ERROR_IO_PKCS11_CKR_INFORMATION_SENSITIVE = ERROR_IO_PKCS11_CKR_SAVED_STATE_INVALID + 1
const ERROR_IO_PKCS11_CKR_STATE_UNSAVEABLE = ERROR_IO_PKCS11_CKR_INFORMATION_SENSITIVE + 1
const ERROR_IO_PKCS11_CKR_CRYPTOKI_NOT_INITIALIZED = ERROR_IO_PKCS11_CKR_STATE_UNSAVEABLE + 1
const ERROR_IO_PKCS11_CKR_CRYPTOKI_ALREADY_INITIALIZED = ERROR_IO_PKCS11_CKR_CRYPTOKI_NOT_INITIALIZED + 1
const ERROR_IO_PKCS11_CKR_MUTEX_BAD = ERROR_IO_PKCS11_CKR_CRYPTOKI_ALREADY_INITIALIZED + 1
const ERROR_IO_PKCS11_CKR_MUTEX_NOT_LOCKED = ERROR_IO_PKCS11_CKR_MUTEX_BAD + 1
const ERROR_IO_PKCS11_CKR_NEW_PIN_MODE = ERROR_IO_PKCS11_CKR_MUTEX_NOT_LOCKED + 1
const ERROR_IO_PKCS11_CKR_NEXT_OTP = ERROR_IO_PKCS11_CKR_NEW_PIN_MODE + 1
const ERROR_IO_PKCS11_CKR_EXCEEDED_MAX_ITERATIONS = ERROR_IO_PKCS11_CKR_NEXT_OTP + 1
const ERROR_IO_PKCS11_CKR_FIPS_SELF_TEST_FAILED = ERROR_IO_PKCS11_CKR_EXCEEDED_MAX_ITERATIONS + 1
const ERROR_IO_PKCS11_CKR_LIBRARY_LOAD_FAILED = ERROR_IO_PKCS11_CKR_FIPS_SELF_TEST_FAILED + 1
const ERROR_IO_PKCS11_CKR_PIN_TOO_WEAK = ERROR_IO_PKCS11_CKR_LIBRARY_LOAD_FAILED + 1
const ERROR_IO_PKCS11_CKR_PUBLIC_KEY_INVALID = ERROR_IO_PKCS11_CKR_PIN_TOO_WEAK + 1
const ERROR_IO_PKCS11_CKR_FUNCTION_REJECTED = ERROR_IO_PKCS11_CKR_PUBLIC_KEY_INVALID + 1
const ERROR_IO_PINNED_EVENT_LOOP_MISMATCH = ERROR_IO_PKCS11_CKR_FUNCTION_REJECTED + 1
const ERROR_IO_PKCS11_ENCODING_ERROR = ERROR_IO_PINNED_EVENT_LOOP_MISMATCH + 1
const ERROR_IO_TLS_ERROR_DEFAULT_TRUST_STORE_NOT_FOUND = ERROR_IO_PKCS11_ENCODING_ERROR + 1
const ERROR_IO_STREAM_SEEK_FAILED = ERROR_IO_TLS_ERROR_DEFAULT_TRUST_STORE_NOT_FOUND + 1
const ERROR_IO_STREAM_GET_LENGTH_FAILED = ERROR_IO_STREAM_SEEK_FAILED + 1
const ERROR_IO_STREAM_SEEK_UNSUPPORTED = ERROR_IO_STREAM_GET_LENGTH_FAILED + 1
const ERROR_IO_STREAM_GET_LENGTH_UNSUPPORTED = ERROR_IO_STREAM_SEEK_UNSUPPORTED + 1
const ERROR_IO_TLS_ERROR_READ_FAILURE = ERROR_IO_STREAM_GET_LENGTH_UNSUPPORTED + 1
const ERROR_IO_PEM_MALFORMED = ERROR_IO_TLS_ERROR_READ_FAILURE + 1
const ERROR_IO_SOCKET_MISSING_EVENT_LOOP = ERROR_IO_PEM_MALFORMED + 1
const ERROR_IO_TLS_UNKNOWN_ROOT_CERTIFICATE = ERROR_IO_SOCKET_MISSING_EVENT_LOOP + 1
const ERROR_IO_TLS_NO_ROOT_CERTIFICATE_FOUND = ERROR_IO_TLS_UNKNOWN_ROOT_CERTIFICATE + 1
const ERROR_IO_TLS_CERTIFICATE_EXPIRED = ERROR_IO_TLS_NO_ROOT_CERTIFICATE_FOUND + 1
const ERROR_IO_TLS_CERTIFICATE_NOT_YET_VALID = ERROR_IO_TLS_CERTIFICATE_EXPIRED + 1
const ERROR_IO_TLS_BAD_CERTIFICATE = ERROR_IO_TLS_CERTIFICATE_NOT_YET_VALID + 1
const ERROR_IO_TLS_PEER_CERTIFICATE_EXPIRED = ERROR_IO_TLS_BAD_CERTIFICATE + 1
const ERROR_IO_TLS_BAD_PEER_CERTIFICATE = ERROR_IO_TLS_PEER_CERTIFICATE_EXPIRED + 1
const ERROR_IO_TLS_PEER_CERTIFICATE_REVOKED = ERROR_IO_TLS_BAD_PEER_CERTIFICATE + 1
const ERROR_IO_TLS_PEER_CERTIFICATE_UNKNOWN = ERROR_IO_TLS_PEER_CERTIFICATE_REVOKED + 1
const ERROR_IO_TLS_INTERNAL_ERROR = ERROR_IO_TLS_PEER_CERTIFICATE_UNKNOWN + 1
const ERROR_IO_TLS_CLOSED_GRACEFUL = ERROR_IO_TLS_INTERNAL_ERROR + 1
const ERROR_IO_TLS_CLOSED_ABORT = ERROR_IO_TLS_CLOSED_GRACEFUL + 1
const ERROR_IO_TLS_INVALID_CERTIFICATE_CHAIN = ERROR_IO_TLS_CLOSED_ABORT + 1
const ERROR_IO_TLS_HOST_NAME_MISMATCH = ERROR_IO_TLS_INVALID_CERTIFICATE_CHAIN + 1
const ERROR_IO_DNS_QUERY_AGAIN = ERROR_IO_TLS_HOST_NAME_MISMATCH + 1
const ERROR_IO_END_RANGE = ERROR_ENUM_END_RANGE(IO_PACKAGE_ID)

# Log subjects for IO operations
const LS_IO_GENERAL = LOG_SUBJECT_BEGIN_RANGE(IO_PACKAGE_ID)
const LS_IO_EVENT_LOOP = LS_IO_GENERAL + 1
const LS_IO_SOCKET = LS_IO_EVENT_LOOP + 1
const LS_IO_SOCKET_HANDLER = LS_IO_SOCKET + 1
const LS_IO_TLS = LS_IO_SOCKET_HANDLER + 1
const LS_IO_ALPN = LS_IO_TLS + 1
const LS_IO_DNS = LS_IO_ALPN + 1
const LS_IO_PKI = LS_IO_DNS + 1
const LS_IO_CHANNEL = LS_IO_PKI + 1
const LS_IO_CHANNEL_BOOTSTRAP = LS_IO_CHANNEL + 1
const LS_IO_FILE_UTILS = LS_IO_CHANNEL_BOOTSTRAP + 1
const LS_IO_SHARED_LIBRARY = LS_IO_FILE_UTILS + 1
const LS_IO_EXPONENTIAL_BACKOFF_RETRY_STRATEGY = LS_IO_SHARED_LIBRARY + 1
const LS_IO_STANDARD_RETRY_STRATEGY = LS_IO_EXPONENTIAL_BACKOFF_RETRY_STRATEGY + 1
const LS_IO_PKCS11 = LS_IO_STANDARD_RETRY_STRATEGY + 1
const LS_IO_PEM = LS_IO_PKCS11 + 1
const LS_IO_LAST = LOG_SUBJECT_END_RANGE(IO_PACKAGE_ID)

# Message type enum
@enumx IoMessageType::UInt8 begin
    APPLICATION_DATA = 0
end

# IO Handle - union of fd (POSIX) or handle (Windows/Apple)
mutable struct IoHandle
    fd::Int32  # File descriptor on POSIX
    handle::Ptr{Cvoid}  # Handle on Windows/Apple
    additional_data::Ptr{Cvoid}
    # set_queue callback - for Apple Network Framework
    set_queue::Ptr{Cvoid}
    # Keep Julia-side handle data alive when additional_data stores pointer_from_objref
    additional_ref::Any
end

function IoHandle()
    return IoHandle(-1, C_NULL, C_NULL, C_NULL, nothing)
end

function IoHandle(fd::Integer)
    return IoHandle(Int32(fd), C_NULL, C_NULL, C_NULL, nothing)
end

io_handle_is_valid(handle::IoHandle) = handle.fd >= 0 || handle.handle != C_NULL

# Forward declarations for types defined in other io files
abstract type AbstractChannel end
abstract type AbstractChannelHandler end
abstract type AbstractEventLoop end

# IO Message - data unit flowing through channel pipeline
mutable struct IoMessage{C <: Union{AbstractChannel, Nothing}, F, U}
    message_data::ByteBuffer
    message_type::IoMessageType.T
    message_tag::Int32
    copy_mark::Csize_t
    owning_channel::C  # nullable
    on_completion::F
    user_data::U
    # Intrusive list node for queueing
    queueing_handle_next::Union{IoMessage, Nothing}  # nullable
    queueing_handle_prev::Union{IoMessage, Nothing}  # nullable
end

function IoMessage(capacity::Integer)
    buf = ByteBuffer(capacity)
    return IoMessage{Nothing, Nothing, Nothing}(
        buf,
        IoMessageType.APPLICATION_DATA,
        Int32(0),
        Csize_t(0),
        nothing,
        nothing,
        nothing,
        nothing,
        nothing,
    )
end

# Clock function type for event loops
const IoClock = Function  # signature: () -> UInt64 (nanoseconds)

# Error definitions for registration
const _io_error_definitions = [
    ("ERROR_IO_CHANNEL_ERROR_CANT_ACCEPT_INPUT", ERROR_IO_CHANNEL_ERROR_CANT_ACCEPT_INPUT, "Channel cannot accept input"),
    ("ERROR_IO_CHANNEL_UNKNOWN_MESSAGE_TYPE", ERROR_IO_CHANNEL_UNKNOWN_MESSAGE_TYPE, "Channel received unknown message type"),
    ("ERROR_IO_CHANNEL_READ_WOULD_EXCEED_WINDOW", ERROR_IO_CHANNEL_READ_WOULD_EXCEED_WINDOW, "Channel read would exceed window"),
    ("ERROR_IO_EVENT_LOOP_ALREADY_ASSIGNED", ERROR_IO_EVENT_LOOP_ALREADY_ASSIGNED, "Event loop already assigned"),
    ("ERROR_IO_EVENT_LOOP_SHUTDOWN", ERROR_IO_EVENT_LOOP_SHUTDOWN, "Event loop shutdown"),
    ("ERROR_IO_TLS_ERROR_NEGOTIATION_FAILURE", ERROR_IO_TLS_ERROR_NEGOTIATION_FAILURE, "TLS negotiation failed"),
    ("ERROR_IO_TLS_ERROR_NOT_NEGOTIATED", ERROR_IO_TLS_ERROR_NOT_NEGOTIATED, "TLS not negotiated"),
    ("ERROR_IO_TLS_ERROR_WRITE_FAILURE", ERROR_IO_TLS_ERROR_WRITE_FAILURE, "TLS write failed"),
    ("ERROR_IO_TLS_ERROR_ALERT_RECEIVED", ERROR_IO_TLS_ERROR_ALERT_RECEIVED, "TLS alert received"),
    ("ERROR_IO_TLS_CTX_ERROR", ERROR_IO_TLS_CTX_ERROR, "TLS context error"),
    ("ERROR_IO_TLS_VERSION_UNSUPPORTED", ERROR_IO_TLS_VERSION_UNSUPPORTED, "TLS version unsupported"),
    ("ERROR_IO_TLS_CIPHER_PREF_UNSUPPORTED", ERROR_IO_TLS_CIPHER_PREF_UNSUPPORTED, "TLS cipher preference unsupported"),
    ("ERROR_IO_MISSING_ALPN_MESSAGE", ERROR_IO_MISSING_ALPN_MESSAGE, "Missing ALPN message"),
    ("ERROR_IO_UNHANDLED_ALPN_PROTOCOL_MESSAGE", ERROR_IO_UNHANDLED_ALPN_PROTOCOL_MESSAGE, "Unhandled ALPN protocol message"),
    ("ERROR_IO_FILE_VALIDATION_FAILURE", ERROR_IO_FILE_VALIDATION_FAILURE, "File validation failure"),
    ("ERROR_IO_EVENT_LOOP_THREAD_ONLY", ERROR_IO_EVENT_LOOP_THREAD_ONLY, "Operation only valid on event loop thread"),
    ("ERROR_IO_ALREADY_SUBSCRIBED", ERROR_IO_ALREADY_SUBSCRIBED, "Already subscribed to IO events"),
    ("ERROR_IO_NOT_SUBSCRIBED", ERROR_IO_NOT_SUBSCRIBED, "Not subscribed to IO events"),
    ("ERROR_IO_OPERATION_CANCELLED", ERROR_IO_OPERATION_CANCELLED, "IO operation cancelled"),
    ("ERROR_IO_READ_WOULD_BLOCK", ERROR_IO_READ_WOULD_BLOCK, "Read would block"),
    ("ERROR_IO_BROKEN_PIPE", ERROR_IO_BROKEN_PIPE, "Broken pipe"),
    ("ERROR_IO_SOCKET_UNSUPPORTED_ADDRESS_FAMILY", ERROR_IO_SOCKET_UNSUPPORTED_ADDRESS_FAMILY, "Socket address family unsupported"),
    ("ERROR_IO_SOCKET_INVALID_OPERATION_FOR_TYPE", ERROR_IO_SOCKET_INVALID_OPERATION_FOR_TYPE, "Invalid operation for socket type"),
    ("ERROR_IO_SOCKET_CONNECTION_REFUSED", ERROR_IO_SOCKET_CONNECTION_REFUSED, "Socket connection refused"),
    ("ERROR_IO_SOCKET_TIMEOUT", ERROR_IO_SOCKET_TIMEOUT, "Socket timeout"),
    ("ERROR_IO_SOCKET_NO_ROUTE_TO_HOST", ERROR_IO_SOCKET_NO_ROUTE_TO_HOST, "No route to host"),
    ("ERROR_IO_SOCKET_NETWORK_DOWN", ERROR_IO_SOCKET_NETWORK_DOWN, "Network down"),
    ("ERROR_IO_SOCKET_CLOSED", ERROR_IO_SOCKET_CLOSED, "Socket closed"),
    ("ERROR_IO_SOCKET_NOT_CONNECTED", ERROR_IO_SOCKET_NOT_CONNECTED, "Socket not connected"),
    ("ERROR_IO_SOCKET_INVALID_OPTIONS", ERROR_IO_SOCKET_INVALID_OPTIONS, "Invalid socket options"),
    ("ERROR_IO_SOCKET_ADDRESS_IN_USE", ERROR_IO_SOCKET_ADDRESS_IN_USE, "Socket address in use"),
    ("ERROR_IO_SOCKET_INVALID_ADDRESS", ERROR_IO_SOCKET_INVALID_ADDRESS, "Invalid socket address"),
    ("ERROR_IO_SOCKET_ILLEGAL_OPERATION_FOR_STATE", ERROR_IO_SOCKET_ILLEGAL_OPERATION_FOR_STATE, "Illegal operation for socket state"),
    ("ERROR_IO_SOCKET_CONNECT_ABORTED", ERROR_IO_SOCKET_CONNECT_ABORTED, "Socket connect aborted"),
    ("ERROR_IO_DNS_QUERY_FAILED", ERROR_IO_DNS_QUERY_FAILED, "DNS query failed"),
    ("ERROR_IO_DNS_INVALID_NAME", ERROR_IO_DNS_INVALID_NAME, "Invalid DNS name"),
    ("ERROR_IO_DNS_NO_ADDRESS_FOR_HOST", ERROR_IO_DNS_NO_ADDRESS_FOR_HOST, "No address for host"),
    ("ERROR_IO_DNS_HOST_REMOVED_FROM_CACHE", ERROR_IO_DNS_HOST_REMOVED_FROM_CACHE, "Host removed from DNS cache"),
    ("ERROR_IO_STREAM_INVALID_SEEK_POSITION", ERROR_IO_STREAM_INVALID_SEEK_POSITION, "Invalid stream seek position"),
    ("ERROR_IO_STREAM_READ_FAILED", ERROR_IO_STREAM_READ_FAILED, "Stream read failed"),
    ("ERROR_IO_INVALID_FILE_HANDLE_DEPRECATED", ERROR_IO_INVALID_FILE_HANDLE_DEPRECATED, "Invalid file handle (deprecated)"),
    ("ERROR_IO_SHARED_LIBRARY_LOAD_FAILURE", ERROR_IO_SHARED_LIBRARY_LOAD_FAILURE, "Shared library load failure"),
    ("ERROR_IO_SHARED_LIBRARY_FIND_SYMBOL_FAILURE", ERROR_IO_SHARED_LIBRARY_FIND_SYMBOL_FAILURE, "Shared library symbol not found"),
    ("ERROR_IO_TLS_NEGOTIATION_TIMEOUT", ERROR_IO_TLS_NEGOTIATION_TIMEOUT, "TLS negotiation timeout"),
    ("ERROR_IO_TLS_ALERT_NOT_GRACEFUL", ERROR_IO_TLS_ALERT_NOT_GRACEFUL, "TLS alert not graceful"),
    ("ERROR_IO_MAX_RETRIES_EXCEEDED", ERROR_IO_MAX_RETRIES_EXCEEDED, "Maximum retries exceeded"),
    ("ERROR_IO_RETRY_PERMISSION_DENIED", ERROR_IO_RETRY_PERMISSION_DENIED, "Retry permission denied"),
    ("ERROR_IO_TLS_DIGEST_ALGORITHM_UNSUPPORTED", ERROR_IO_TLS_DIGEST_ALGORITHM_UNSUPPORTED, "TLS digest algorithm unsupported"),
    ("ERROR_IO_TLS_SIGNATURE_ALGORITHM_UNSUPPORTED", ERROR_IO_TLS_SIGNATURE_ALGORITHM_UNSUPPORTED, "TLS signature algorithm unsupported"),
    ("ERROR_IO_PKCS11_VERSION_UNSUPPORTED", ERROR_IO_PKCS11_VERSION_UNSUPPORTED, "PKCS#11 version unsupported"),
    ("ERROR_IO_PKCS11_TOKEN_NOT_FOUND", ERROR_IO_PKCS11_TOKEN_NOT_FOUND, "PKCS#11 token not found"),
    ("ERROR_IO_PKCS11_KEY_NOT_FOUND", ERROR_IO_PKCS11_KEY_NOT_FOUND, "PKCS#11 key not found"),
    ("ERROR_IO_PKCS11_KEY_TYPE_UNSUPPORTED", ERROR_IO_PKCS11_KEY_TYPE_UNSUPPORTED, "PKCS#11 key type unsupported"),
    ("ERROR_IO_PKCS11_UNKNOWN_CRYPTOKI_RETURN_VALUE", ERROR_IO_PKCS11_UNKNOWN_CRYPTOKI_RETURN_VALUE, "Unknown PKCS#11 Cryptoki return value"),
    # PKCS#11 CKR errors (abbreviated for brevity - full list included)
    ("ERROR_IO_PKCS11_CKR_CANCEL", ERROR_IO_PKCS11_CKR_CANCEL, "PKCS#11 CKR_CANCEL"),
    ("ERROR_IO_PKCS11_CKR_HOST_MEMORY", ERROR_IO_PKCS11_CKR_HOST_MEMORY, "PKCS#11 CKR_HOST_MEMORY"),
    ("ERROR_IO_PKCS11_CKR_SLOT_ID_INVALID", ERROR_IO_PKCS11_CKR_SLOT_ID_INVALID, "PKCS#11 CKR_SLOT_ID_INVALID"),
    ("ERROR_IO_PKCS11_CKR_GENERAL_ERROR", ERROR_IO_PKCS11_CKR_GENERAL_ERROR, "PKCS#11 CKR_GENERAL_ERROR"),
    ("ERROR_IO_PKCS11_CKR_FUNCTION_FAILED", ERROR_IO_PKCS11_CKR_FUNCTION_FAILED, "PKCS#11 CKR_FUNCTION_FAILED"),
    ("ERROR_IO_PKCS11_CKR_ARGUMENTS_BAD", ERROR_IO_PKCS11_CKR_ARGUMENTS_BAD, "PKCS#11 CKR_ARGUMENTS_BAD"),
    ("ERROR_IO_PKCS11_CKR_NO_EVENT", ERROR_IO_PKCS11_CKR_NO_EVENT, "PKCS#11 CKR_NO_EVENT"),
    ("ERROR_IO_PKCS11_CKR_NEED_TO_CREATE_THREADS", ERROR_IO_PKCS11_CKR_NEED_TO_CREATE_THREADS, "PKCS#11 CKR_NEED_TO_CREATE_THREADS"),
    ("ERROR_IO_PKCS11_CKR_CANT_LOCK", ERROR_IO_PKCS11_CKR_CANT_LOCK, "PKCS#11 CKR_CANT_LOCK"),
    ("ERROR_IO_PKCS11_CKR_ATTRIBUTE_READ_ONLY", ERROR_IO_PKCS11_CKR_ATTRIBUTE_READ_ONLY, "PKCS#11 CKR_ATTRIBUTE_READ_ONLY"),
    ("ERROR_IO_PKCS11_CKR_ATTRIBUTE_SENSITIVE", ERROR_IO_PKCS11_CKR_ATTRIBUTE_SENSITIVE, "PKCS#11 CKR_ATTRIBUTE_SENSITIVE"),
    ("ERROR_IO_PKCS11_CKR_ATTRIBUTE_TYPE_INVALID", ERROR_IO_PKCS11_CKR_ATTRIBUTE_TYPE_INVALID, "PKCS#11 CKR_ATTRIBUTE_TYPE_INVALID"),
    ("ERROR_IO_PKCS11_CKR_ATTRIBUTE_VALUE_INVALID", ERROR_IO_PKCS11_CKR_ATTRIBUTE_VALUE_INVALID, "PKCS#11 CKR_ATTRIBUTE_VALUE_INVALID"),
    ("ERROR_IO_PKCS11_CKR_ACTION_PROHIBITED", ERROR_IO_PKCS11_CKR_ACTION_PROHIBITED, "PKCS#11 CKR_ACTION_PROHIBITED"),
    ("ERROR_IO_PKCS11_CKR_DATA_INVALID", ERROR_IO_PKCS11_CKR_DATA_INVALID, "PKCS#11 CKR_DATA_INVALID"),
    ("ERROR_IO_PKCS11_CKR_DATA_LEN_RANGE", ERROR_IO_PKCS11_CKR_DATA_LEN_RANGE, "PKCS#11 CKR_DATA_LEN_RANGE"),
    ("ERROR_IO_PKCS11_CKR_DEVICE_ERROR", ERROR_IO_PKCS11_CKR_DEVICE_ERROR, "PKCS#11 CKR_DEVICE_ERROR"),
    ("ERROR_IO_PKCS11_CKR_DEVICE_MEMORY", ERROR_IO_PKCS11_CKR_DEVICE_MEMORY, "PKCS#11 CKR_DEVICE_MEMORY"),
    ("ERROR_IO_PKCS11_CKR_DEVICE_REMOVED", ERROR_IO_PKCS11_CKR_DEVICE_REMOVED, "PKCS#11 CKR_DEVICE_REMOVED"),
    ("ERROR_IO_PKCS11_CKR_ENCRYPTED_DATA_INVALID", ERROR_IO_PKCS11_CKR_ENCRYPTED_DATA_INVALID, "PKCS#11 CKR_ENCRYPTED_DATA_INVALID"),
    ("ERROR_IO_PKCS11_CKR_ENCRYPTED_DATA_LEN_RANGE", ERROR_IO_PKCS11_CKR_ENCRYPTED_DATA_LEN_RANGE, "PKCS#11 CKR_ENCRYPTED_DATA_LEN_RANGE"),
    ("ERROR_IO_PKCS11_CKR_FUNCTION_CANCELED", ERROR_IO_PKCS11_CKR_FUNCTION_CANCELED, "PKCS#11 CKR_FUNCTION_CANCELED"),
    ("ERROR_IO_PKCS11_CKR_FUNCTION_NOT_PARALLEL", ERROR_IO_PKCS11_CKR_FUNCTION_NOT_PARALLEL, "PKCS#11 CKR_FUNCTION_NOT_PARALLEL"),
    ("ERROR_IO_PKCS11_CKR_FUNCTION_NOT_SUPPORTED", ERROR_IO_PKCS11_CKR_FUNCTION_NOT_SUPPORTED, "PKCS#11 CKR_FUNCTION_NOT_SUPPORTED"),
    ("ERROR_IO_PKCS11_CKR_KEY_HANDLE_INVALID", ERROR_IO_PKCS11_CKR_KEY_HANDLE_INVALID, "PKCS#11 CKR_KEY_HANDLE_INVALID"),
    ("ERROR_IO_PKCS11_CKR_KEY_SIZE_RANGE", ERROR_IO_PKCS11_CKR_KEY_SIZE_RANGE, "PKCS#11 CKR_KEY_SIZE_RANGE"),
    ("ERROR_IO_PKCS11_CKR_KEY_TYPE_INCONSISTENT", ERROR_IO_PKCS11_CKR_KEY_TYPE_INCONSISTENT, "PKCS#11 CKR_KEY_TYPE_INCONSISTENT"),
    ("ERROR_IO_PKCS11_CKR_KEY_NOT_NEEDED", ERROR_IO_PKCS11_CKR_KEY_NOT_NEEDED, "PKCS#11 CKR_KEY_NOT_NEEDED"),
    ("ERROR_IO_PKCS11_CKR_KEY_CHANGED", ERROR_IO_PKCS11_CKR_KEY_CHANGED, "PKCS#11 CKR_KEY_CHANGED"),
    ("ERROR_IO_PKCS11_CKR_KEY_NEEDED", ERROR_IO_PKCS11_CKR_KEY_NEEDED, "PKCS#11 CKR_KEY_NEEDED"),
    ("ERROR_IO_PKCS11_CKR_KEY_INDIGESTIBLE", ERROR_IO_PKCS11_CKR_KEY_INDIGESTIBLE, "PKCS#11 CKR_KEY_INDIGESTIBLE"),
    ("ERROR_IO_PKCS11_CKR_KEY_FUNCTION_NOT_PERMITTED", ERROR_IO_PKCS11_CKR_KEY_FUNCTION_NOT_PERMITTED, "PKCS#11 CKR_KEY_FUNCTION_NOT_PERMITTED"),
    ("ERROR_IO_PKCS11_CKR_KEY_NOT_WRAPPABLE", ERROR_IO_PKCS11_CKR_KEY_NOT_WRAPPABLE, "PKCS#11 CKR_KEY_NOT_WRAPPABLE"),
    ("ERROR_IO_PKCS11_CKR_KEY_UNEXTRACTABLE", ERROR_IO_PKCS11_CKR_KEY_UNEXTRACTABLE, "PKCS#11 CKR_KEY_UNEXTRACTABLE"),
    ("ERROR_IO_PKCS11_CKR_MECHANISM_INVALID", ERROR_IO_PKCS11_CKR_MECHANISM_INVALID, "PKCS#11 CKR_MECHANISM_INVALID"),
    ("ERROR_IO_PKCS11_CKR_MECHANISM_PARAM_INVALID", ERROR_IO_PKCS11_CKR_MECHANISM_PARAM_INVALID, "PKCS#11 CKR_MECHANISM_PARAM_INVALID"),
    ("ERROR_IO_PKCS11_CKR_OBJECT_HANDLE_INVALID", ERROR_IO_PKCS11_CKR_OBJECT_HANDLE_INVALID, "PKCS#11 CKR_OBJECT_HANDLE_INVALID"),
    ("ERROR_IO_PKCS11_CKR_OPERATION_ACTIVE", ERROR_IO_PKCS11_CKR_OPERATION_ACTIVE, "PKCS#11 CKR_OPERATION_ACTIVE"),
    ("ERROR_IO_PKCS11_CKR_OPERATION_NOT_INITIALIZED", ERROR_IO_PKCS11_CKR_OPERATION_NOT_INITIALIZED, "PKCS#11 CKR_OPERATION_NOT_INITIALIZED"),
    ("ERROR_IO_PKCS11_CKR_PIN_INCORRECT", ERROR_IO_PKCS11_CKR_PIN_INCORRECT, "PKCS#11 CKR_PIN_INCORRECT"),
    ("ERROR_IO_PKCS11_CKR_PIN_INVALID", ERROR_IO_PKCS11_CKR_PIN_INVALID, "PKCS#11 CKR_PIN_INVALID"),
    ("ERROR_IO_PKCS11_CKR_PIN_LEN_RANGE", ERROR_IO_PKCS11_CKR_PIN_LEN_RANGE, "PKCS#11 CKR_PIN_LEN_RANGE"),
    ("ERROR_IO_PKCS11_CKR_PIN_EXPIRED", ERROR_IO_PKCS11_CKR_PIN_EXPIRED, "PKCS#11 CKR_PIN_EXPIRED"),
    ("ERROR_IO_PKCS11_CKR_PIN_LOCKED", ERROR_IO_PKCS11_CKR_PIN_LOCKED, "PKCS#11 CKR_PIN_LOCKED"),
    ("ERROR_IO_PKCS11_CKR_SESSION_CLOSED", ERROR_IO_PKCS11_CKR_SESSION_CLOSED, "PKCS#11 CKR_SESSION_CLOSED"),
    ("ERROR_IO_PKCS11_CKR_SESSION_COUNT", ERROR_IO_PKCS11_CKR_SESSION_COUNT, "PKCS#11 CKR_SESSION_COUNT"),
    ("ERROR_IO_PKCS11_CKR_SESSION_HANDLE_INVALID", ERROR_IO_PKCS11_CKR_SESSION_HANDLE_INVALID, "PKCS#11 CKR_SESSION_HANDLE_INVALID"),
    ("ERROR_IO_PKCS11_CKR_SESSION_PARALLEL_NOT_SUPPORTED", ERROR_IO_PKCS11_CKR_SESSION_PARALLEL_NOT_SUPPORTED, "PKCS#11 CKR_SESSION_PARALLEL_NOT_SUPPORTED"),
    ("ERROR_IO_PKCS11_CKR_SESSION_READ_ONLY", ERROR_IO_PKCS11_CKR_SESSION_READ_ONLY, "PKCS#11 CKR_SESSION_READ_ONLY"),
    ("ERROR_IO_PKCS11_CKR_SESSION_EXISTS", ERROR_IO_PKCS11_CKR_SESSION_EXISTS, "PKCS#11 CKR_SESSION_EXISTS"),
    ("ERROR_IO_PKCS11_CKR_SESSION_READ_ONLY_EXISTS", ERROR_IO_PKCS11_CKR_SESSION_READ_ONLY_EXISTS, "PKCS#11 CKR_SESSION_READ_ONLY_EXISTS"),
    ("ERROR_IO_PKCS11_CKR_SESSION_READ_WRITE_SO_EXISTS", ERROR_IO_PKCS11_CKR_SESSION_READ_WRITE_SO_EXISTS, "PKCS#11 CKR_SESSION_READ_WRITE_SO_EXISTS"),
    ("ERROR_IO_PKCS11_CKR_SIGNATURE_INVALID", ERROR_IO_PKCS11_CKR_SIGNATURE_INVALID, "PKCS#11 CKR_SIGNATURE_INVALID"),
    ("ERROR_IO_PKCS11_CKR_SIGNATURE_LEN_RANGE", ERROR_IO_PKCS11_CKR_SIGNATURE_LEN_RANGE, "PKCS#11 CKR_SIGNATURE_LEN_RANGE"),
    ("ERROR_IO_PKCS11_CKR_TEMPLATE_INCOMPLETE", ERROR_IO_PKCS11_CKR_TEMPLATE_INCOMPLETE, "PKCS#11 CKR_TEMPLATE_INCOMPLETE"),
    ("ERROR_IO_PKCS11_CKR_TEMPLATE_INCONSISTENT", ERROR_IO_PKCS11_CKR_TEMPLATE_INCONSISTENT, "PKCS#11 CKR_TEMPLATE_INCONSISTENT"),
    ("ERROR_IO_PKCS11_CKR_TOKEN_NOT_PRESENT", ERROR_IO_PKCS11_CKR_TOKEN_NOT_PRESENT, "PKCS#11 CKR_TOKEN_NOT_PRESENT"),
    ("ERROR_IO_PKCS11_CKR_TOKEN_NOT_RECOGNIZED", ERROR_IO_PKCS11_CKR_TOKEN_NOT_RECOGNIZED, "PKCS#11 CKR_TOKEN_NOT_RECOGNIZED"),
    ("ERROR_IO_PKCS11_CKR_TOKEN_WRITE_PROTECTED", ERROR_IO_PKCS11_CKR_TOKEN_WRITE_PROTECTED, "PKCS#11 CKR_TOKEN_WRITE_PROTECTED"),
    ("ERROR_IO_PKCS11_CKR_UNWRAPPING_KEY_HANDLE_INVALID", ERROR_IO_PKCS11_CKR_UNWRAPPING_KEY_HANDLE_INVALID, "PKCS#11 CKR_UNWRAPPING_KEY_HANDLE_INVALID"),
    ("ERROR_IO_PKCS11_CKR_UNWRAPPING_KEY_SIZE_RANGE", ERROR_IO_PKCS11_CKR_UNWRAPPING_KEY_SIZE_RANGE, "PKCS#11 CKR_UNWRAPPING_KEY_SIZE_RANGE"),
    ("ERROR_IO_PKCS11_CKR_UNWRAPPING_KEY_TYPE_INCONSISTENT", ERROR_IO_PKCS11_CKR_UNWRAPPING_KEY_TYPE_INCONSISTENT, "PKCS#11 CKR_UNWRAPPING_KEY_TYPE_INCONSISTENT"),
    ("ERROR_IO_PKCS11_CKR_USER_ALREADY_LOGGED_IN", ERROR_IO_PKCS11_CKR_USER_ALREADY_LOGGED_IN, "PKCS#11 CKR_USER_ALREADY_LOGGED_IN"),
    ("ERROR_IO_PKCS11_CKR_USER_NOT_LOGGED_IN", ERROR_IO_PKCS11_CKR_USER_NOT_LOGGED_IN, "PKCS#11 CKR_USER_NOT_LOGGED_IN"),
    ("ERROR_IO_PKCS11_CKR_USER_PIN_NOT_INITIALIZED", ERROR_IO_PKCS11_CKR_USER_PIN_NOT_INITIALIZED, "PKCS#11 CKR_USER_PIN_NOT_INITIALIZED"),
    ("ERROR_IO_PKCS11_CKR_USER_TYPE_INVALID", ERROR_IO_PKCS11_CKR_USER_TYPE_INVALID, "PKCS#11 CKR_USER_TYPE_INVALID"),
    ("ERROR_IO_PKCS11_CKR_USER_ANOTHER_ALREADY_LOGGED_IN", ERROR_IO_PKCS11_CKR_USER_ANOTHER_ALREADY_LOGGED_IN, "PKCS#11 CKR_USER_ANOTHER_ALREADY_LOGGED_IN"),
    ("ERROR_IO_PKCS11_CKR_USER_TOO_MANY_TYPES", ERROR_IO_PKCS11_CKR_USER_TOO_MANY_TYPES, "PKCS#11 CKR_USER_TOO_MANY_TYPES"),
    ("ERROR_IO_PKCS11_CKR_WRAPPED_KEY_INVALID", ERROR_IO_PKCS11_CKR_WRAPPED_KEY_INVALID, "PKCS#11 CKR_WRAPPED_KEY_INVALID"),
    ("ERROR_IO_PKCS11_CKR_WRAPPED_KEY_LEN_RANGE", ERROR_IO_PKCS11_CKR_WRAPPED_KEY_LEN_RANGE, "PKCS#11 CKR_WRAPPED_KEY_LEN_RANGE"),
    ("ERROR_IO_PKCS11_CKR_WRAPPING_KEY_HANDLE_INVALID", ERROR_IO_PKCS11_CKR_WRAPPING_KEY_HANDLE_INVALID, "PKCS#11 CKR_WRAPPING_KEY_HANDLE_INVALID"),
    ("ERROR_IO_PKCS11_CKR_WRAPPING_KEY_SIZE_RANGE", ERROR_IO_PKCS11_CKR_WRAPPING_KEY_SIZE_RANGE, "PKCS#11 CKR_WRAPPING_KEY_SIZE_RANGE"),
    ("ERROR_IO_PKCS11_CKR_WRAPPING_KEY_TYPE_INCONSISTENT", ERROR_IO_PKCS11_CKR_WRAPPING_KEY_TYPE_INCONSISTENT, "PKCS#11 CKR_WRAPPING_KEY_TYPE_INCONSISTENT"),
    ("ERROR_IO_PKCS11_CKR_RANDOM_SEED_NOT_SUPPORTED", ERROR_IO_PKCS11_CKR_RANDOM_SEED_NOT_SUPPORTED, "PKCS#11 CKR_RANDOM_SEED_NOT_SUPPORTED"),
    ("ERROR_IO_PKCS11_CKR_RANDOM_NO_RNG", ERROR_IO_PKCS11_CKR_RANDOM_NO_RNG, "PKCS#11 CKR_RANDOM_NO_RNG"),
    ("ERROR_IO_PKCS11_CKR_DOMAIN_PARAMS_INVALID", ERROR_IO_PKCS11_CKR_DOMAIN_PARAMS_INVALID, "PKCS#11 CKR_DOMAIN_PARAMS_INVALID"),
    ("ERROR_IO_PKCS11_CKR_CURVE_NOT_SUPPORTED", ERROR_IO_PKCS11_CKR_CURVE_NOT_SUPPORTED, "PKCS#11 CKR_CURVE_NOT_SUPPORTED"),
    ("ERROR_IO_PKCS11_CKR_BUFFER_TOO_SMALL", ERROR_IO_PKCS11_CKR_BUFFER_TOO_SMALL, "PKCS#11 CKR_BUFFER_TOO_SMALL"),
    ("ERROR_IO_PKCS11_CKR_SAVED_STATE_INVALID", ERROR_IO_PKCS11_CKR_SAVED_STATE_INVALID, "PKCS#11 CKR_SAVED_STATE_INVALID"),
    ("ERROR_IO_PKCS11_CKR_INFORMATION_SENSITIVE", ERROR_IO_PKCS11_CKR_INFORMATION_SENSITIVE, "PKCS#11 CKR_INFORMATION_SENSITIVE"),
    ("ERROR_IO_PKCS11_CKR_STATE_UNSAVEABLE", ERROR_IO_PKCS11_CKR_STATE_UNSAVEABLE, "PKCS#11 CKR_STATE_UNSAVEABLE"),
    ("ERROR_IO_PKCS11_CKR_CRYPTOKI_NOT_INITIALIZED", ERROR_IO_PKCS11_CKR_CRYPTOKI_NOT_INITIALIZED, "PKCS#11 CKR_CRYPTOKI_NOT_INITIALIZED"),
    ("ERROR_IO_PKCS11_CKR_CRYPTOKI_ALREADY_INITIALIZED", ERROR_IO_PKCS11_CKR_CRYPTOKI_ALREADY_INITIALIZED, "PKCS#11 CKR_CRYPTOKI_ALREADY_INITIALIZED"),
    ("ERROR_IO_PKCS11_CKR_MUTEX_BAD", ERROR_IO_PKCS11_CKR_MUTEX_BAD, "PKCS#11 CKR_MUTEX_BAD"),
    ("ERROR_IO_PKCS11_CKR_MUTEX_NOT_LOCKED", ERROR_IO_PKCS11_CKR_MUTEX_NOT_LOCKED, "PKCS#11 CKR_MUTEX_NOT_LOCKED"),
    ("ERROR_IO_PKCS11_CKR_NEW_PIN_MODE", ERROR_IO_PKCS11_CKR_NEW_PIN_MODE, "PKCS#11 CKR_NEW_PIN_MODE"),
    ("ERROR_IO_PKCS11_CKR_NEXT_OTP", ERROR_IO_PKCS11_CKR_NEXT_OTP, "PKCS#11 CKR_NEXT_OTP"),
    ("ERROR_IO_PKCS11_CKR_EXCEEDED_MAX_ITERATIONS", ERROR_IO_PKCS11_CKR_EXCEEDED_MAX_ITERATIONS, "PKCS#11 CKR_EXCEEDED_MAX_ITERATIONS"),
    ("ERROR_IO_PKCS11_CKR_FIPS_SELF_TEST_FAILED", ERROR_IO_PKCS11_CKR_FIPS_SELF_TEST_FAILED, "PKCS#11 CKR_FIPS_SELF_TEST_FAILED"),
    ("ERROR_IO_PKCS11_CKR_LIBRARY_LOAD_FAILED", ERROR_IO_PKCS11_CKR_LIBRARY_LOAD_FAILED, "PKCS#11 CKR_LIBRARY_LOAD_FAILED"),
    ("ERROR_IO_PKCS11_CKR_PIN_TOO_WEAK", ERROR_IO_PKCS11_CKR_PIN_TOO_WEAK, "PKCS#11 CKR_PIN_TOO_WEAK"),
    ("ERROR_IO_PKCS11_CKR_PUBLIC_KEY_INVALID", ERROR_IO_PKCS11_CKR_PUBLIC_KEY_INVALID, "PKCS#11 CKR_PUBLIC_KEY_INVALID"),
    ("ERROR_IO_PKCS11_CKR_FUNCTION_REJECTED", ERROR_IO_PKCS11_CKR_FUNCTION_REJECTED, "PKCS#11 CKR_FUNCTION_REJECTED"),
    ("ERROR_IO_PINNED_EVENT_LOOP_MISMATCH", ERROR_IO_PINNED_EVENT_LOOP_MISMATCH, "Pinned event loop mismatch"),
    ("ERROR_IO_PKCS11_ENCODING_ERROR", ERROR_IO_PKCS11_ENCODING_ERROR, "PKCS#11 encoding error"),
    ("ERROR_IO_TLS_ERROR_DEFAULT_TRUST_STORE_NOT_FOUND", ERROR_IO_TLS_ERROR_DEFAULT_TRUST_STORE_NOT_FOUND, "TLS default trust store not found"),
    ("ERROR_IO_STREAM_SEEK_FAILED", ERROR_IO_STREAM_SEEK_FAILED, "Stream seek failed"),
    ("ERROR_IO_STREAM_GET_LENGTH_FAILED", ERROR_IO_STREAM_GET_LENGTH_FAILED, "Stream get length failed"),
    ("ERROR_IO_STREAM_SEEK_UNSUPPORTED", ERROR_IO_STREAM_SEEK_UNSUPPORTED, "Stream seek unsupported"),
    ("ERROR_IO_STREAM_GET_LENGTH_UNSUPPORTED", ERROR_IO_STREAM_GET_LENGTH_UNSUPPORTED, "Stream get length unsupported"),
    ("ERROR_IO_TLS_ERROR_READ_FAILURE", ERROR_IO_TLS_ERROR_READ_FAILURE, "TLS read failure"),
    ("ERROR_IO_PEM_MALFORMED", ERROR_IO_PEM_MALFORMED, "Malformed PEM"),
    ("ERROR_IO_SOCKET_MISSING_EVENT_LOOP", ERROR_IO_SOCKET_MISSING_EVENT_LOOP, "Socket missing event loop"),
    ("ERROR_IO_TLS_UNKNOWN_ROOT_CERTIFICATE", ERROR_IO_TLS_UNKNOWN_ROOT_CERTIFICATE, "TLS unknown root certificate"),
    ("ERROR_IO_TLS_NO_ROOT_CERTIFICATE_FOUND", ERROR_IO_TLS_NO_ROOT_CERTIFICATE_FOUND, "TLS no root certificate found"),
    ("ERROR_IO_TLS_CERTIFICATE_EXPIRED", ERROR_IO_TLS_CERTIFICATE_EXPIRED, "TLS certificate expired"),
    ("ERROR_IO_TLS_CERTIFICATE_NOT_YET_VALID", ERROR_IO_TLS_CERTIFICATE_NOT_YET_VALID, "TLS certificate not yet valid"),
    ("ERROR_IO_TLS_BAD_CERTIFICATE", ERROR_IO_TLS_BAD_CERTIFICATE, "TLS bad certificate"),
    ("ERROR_IO_TLS_PEER_CERTIFICATE_EXPIRED", ERROR_IO_TLS_PEER_CERTIFICATE_EXPIRED, "TLS peer certificate expired"),
    ("ERROR_IO_TLS_BAD_PEER_CERTIFICATE", ERROR_IO_TLS_BAD_PEER_CERTIFICATE, "TLS bad peer certificate"),
    ("ERROR_IO_TLS_PEER_CERTIFICATE_REVOKED", ERROR_IO_TLS_PEER_CERTIFICATE_REVOKED, "TLS peer certificate revoked"),
    ("ERROR_IO_TLS_PEER_CERTIFICATE_UNKNOWN", ERROR_IO_TLS_PEER_CERTIFICATE_UNKNOWN, "TLS peer certificate unknown"),
    ("ERROR_IO_TLS_INTERNAL_ERROR", ERROR_IO_TLS_INTERNAL_ERROR, "TLS internal error"),
    ("ERROR_IO_TLS_CLOSED_GRACEFUL", ERROR_IO_TLS_CLOSED_GRACEFUL, "TLS closed gracefully"),
    ("ERROR_IO_TLS_CLOSED_ABORT", ERROR_IO_TLS_CLOSED_ABORT, "TLS closed with abort"),
    ("ERROR_IO_TLS_INVALID_CERTIFICATE_CHAIN", ERROR_IO_TLS_INVALID_CERTIFICATE_CHAIN, "TLS invalid certificate chain"),
    ("ERROR_IO_TLS_HOST_NAME_MISMATCH", ERROR_IO_TLS_HOST_NAME_MISMATCH, "TLS host name mismatch"),
    ("ERROR_IO_DNS_QUERY_AGAIN", ERROR_IO_DNS_QUERY_AGAIN, "DNS query should be retried"),
]

const _io_error_entries = let
    count = ERROR_IO_DNS_QUERY_AGAIN - ERROR_IO_CHANNEL_ERROR_CANT_ACCEPT_INPUT + 1
    entries = Memory{error_info}(undef, count)
    for (name, code, msg) in _io_error_definitions
        idx = code - ERROR_IO_CHANNEL_ERROR_CANT_ACCEPT_INPUT + 1
        entries[idx] = _define_error_info(code, name, msg, "aws-c-io")
    end
    entries
end

const _io_error_list_ref = Ref{error_info_list}(
    error_info_list(pointer(_io_error_entries), UInt16(length(_io_error_entries))),
)

const _io_log_subject_infos = let infos = Memory{LogSubjectInfo}(undef, 16)
    infos[1] = LogSubjectInfo(LS_IO_GENERAL, "IO", "Subject for general IO logging")
    infos[2] = LogSubjectInfo(LS_IO_EVENT_LOOP, "EventLoop", "Subject for event loop logging")
    infos[3] = LogSubjectInfo(LS_IO_SOCKET, "Socket", "Subject for socket logging")
    infos[4] = LogSubjectInfo(LS_IO_SOCKET_HANDLER, "SocketHandler", "Subject for socket handler logging")
    infos[5] = LogSubjectInfo(LS_IO_TLS, "TLS", "Subject for TLS logging")
    infos[6] = LogSubjectInfo(LS_IO_ALPN, "ALPN", "Subject for ALPN logging")
    infos[7] = LogSubjectInfo(LS_IO_DNS, "DNS", "Subject for DNS logging")
    infos[8] = LogSubjectInfo(LS_IO_PKI, "PKI", "Subject for PKI logging")
    infos[9] = LogSubjectInfo(LS_IO_CHANNEL, "Channel", "Subject for channel logging")
    infos[10] = LogSubjectInfo(LS_IO_CHANNEL_BOOTSTRAP, "ChannelBootstrap", "Subject for channel bootstrap logging")
    infos[11] = LogSubjectInfo(LS_IO_FILE_UTILS, "FileUtils", "Subject for file utilities logging")
    infos[12] = LogSubjectInfo(LS_IO_SHARED_LIBRARY, "SharedLib", "Subject for shared library logging")
    infos[13] = LogSubjectInfo(LS_IO_EXPONENTIAL_BACKOFF_RETRY_STRATEGY, "ExponentialBackoff", "Subject for exponential backoff retry strategy")
    infos[14] = LogSubjectInfo(LS_IO_STANDARD_RETRY_STRATEGY, "StandardRetry", "Subject for standard retry strategy")
    infos[15] = LogSubjectInfo(LS_IO_PKCS11, "PKCS11", "Subject for PKCS#11 logging")
    infos[16] = LogSubjectInfo(LS_IO_PEM, "PEM", "Subject for PEM logging")
    infos
end

const _io_log_subject_list = LogSubjectInfoList(_io_log_subject_infos)

const _io_init_count = Ref{Int}(0)

function _io_init()
    count = _io_init_count[]
    _io_init_count[] = count + 1
    if count != 0
        return nothing
    end
    _common_init()
    _cal_init()
    register_error_info(Base.unsafe_convert(Ptr{error_info_list}, _io_error_list_ref))
    register_log_subject_info_list(_io_log_subject_list)
    return nothing
end

function _io_cleanup()
    count = _io_init_count[] - 1
    _io_init_count[] = count
    if count != 0
        return nothing
    end
    unregister_log_subject_info_list(_io_log_subject_list)
    unregister_error_info(Base.unsafe_convert(Ptr{error_info_list}, _io_error_list_ref))
    _cal_cleanup()
    _common_cleanup()
    return nothing
end

# Helper for determining if an error code is retryable
function io_error_code_is_retryable(error_code::Integer)::Bool
    return error_code == ERROR_IO_SOCKET_CONNECTION_REFUSED ||
        error_code == ERROR_IO_SOCKET_TIMEOUT ||
        error_code == ERROR_IO_SOCKET_NO_ROUTE_TO_HOST ||
        error_code == ERROR_IO_SOCKET_NETWORK_DOWN ||
        error_code == ERROR_IO_SOCKET_CLOSED ||
        error_code == ERROR_IO_SOCKET_NOT_CONNECTED ||
        error_code == ERROR_IO_SOCKET_CONNECT_ABORTED ||
        error_code == ERROR_IO_DNS_QUERY_FAILED ||
        error_code == ERROR_IO_DNS_NO_ADDRESS_FOR_HOST ||
        error_code == ERROR_IO_DNS_QUERY_AGAIN ||
        error_code == ERROR_IO_TLS_ERROR_NEGOTIATION_FAILURE ||
        error_code == ERROR_IO_TLS_NEGOTIATION_TIMEOUT ||
        error_code == ERROR_IO_TLS_CLOSED_ABORT ||
        error_code == ERROR_IO_BROKEN_PIPE ||
        error_code == ERROR_IO_READ_WOULD_BLOCK
end

# Include event loop abstractions and platform-specific implementations
include("event_loop.jl")
include("kqueue_event_loop.jl")
include("epoll_event_loop.jl")
include("message_pool.jl")
include("socket.jl")
include("posix_socket.jl")
include("channel.jl")
include("socket_channel_handler.jl")
include("host_resolver.jl")
include("retry_strategy.jl")
include("stream.jl")
include("pem.jl")
include("pipe.jl")
include("shared_library.jl")
include("future.jl")
include("channel_bootstrap.jl")
