const OP_SUCCESS = 0
const OP_ERR = -1

const ERROR_ENUM_STRIDE_BITS = 10
const ERROR_ENUM_STRIDE = 1 << ERROR_ENUM_STRIDE_BITS
ERROR_ENUM_BEGIN_RANGE(x) = x * ERROR_ENUM_STRIDE
ERROR_ENUM_END_RANGE(x) = ((x + 1) * ERROR_ENUM_STRIDE) - 1

const COMMON_PACKAGE_ID = 0

const ERROR_SUCCESS = ERROR_ENUM_BEGIN_RANGE(COMMON_PACKAGE_ID)
const ERROR_OOM = ERROR_SUCCESS + 1
const ERROR_NO_SPACE = ERROR_SUCCESS + 2
const ERROR_UNKNOWN = ERROR_SUCCESS + 3
const ERROR_SHORT_BUFFER = ERROR_SUCCESS + 4
const ERROR_OVERFLOW_DETECTED = ERROR_SUCCESS + 5
const ERROR_INVALID_BUFFER_SIZE = ERROR_SUCCESS + 7
const ERROR_THREAD_NO_SUCH_THREAD_ID = ERROR_SUCCESS + 15
const ERROR_COND_VARIABLE_TIMED_OUT = ERROR_SUCCESS + 22
const ERROR_CLOCK_FAILURE = ERROR_SUCCESS + 24
const ERROR_DEST_COPY_TOO_SMALL = ERROR_SUCCESS + 26
const ERROR_INVALID_ARGUMENT = ERROR_SUCCESS + 34
const ERROR_UNIMPLEMENTED = ERROR_SUCCESS + 37
const ERROR_INVALID_STATE = ERROR_SUCCESS + 38
const ERROR_STREAM_UNSEEKABLE = ERROR_SUCCESS + 42
const ERROR_NO_PERMISSION = ERROR_SUCCESS + 43
const ERROR_FILE_INVALID_PATH = ERROR_SUCCESS + 44
const ERROR_MAX_FDS_EXCEEDED = ERROR_SUCCESS + 45
const ERROR_SYS_CALL_FAILURE = ERROR_SUCCESS + 46
const ERROR_STRING_MATCH_NOT_FOUND = ERROR_SUCCESS + 48
const ERROR_INVALID_FILE_HANDLE = ERROR_SUCCESS + 50
const ERROR_DIRECTORY_NOT_EMPTY = ERROR_SUCCESS + 52
const ERROR_PLATFORM_NOT_SUPPORTED = ERROR_SUCCESS + 53
const ERROR_FILE_OPEN_FAILURE = ERROR_SUCCESS + 57
const ERROR_FILE_READ_FAILURE = ERROR_SUCCESS + 58

const IO_PACKAGE_ID = 1

# Error codes for IO operations
const ERROR_IO_CHANNEL_ERROR_CANT_ACCEPT_INPUT = ERROR_ENUM_BEGIN_RANGE(IO_PACKAGE_ID)
const ERROR_IO_CHANNEL_UNKNOWN_MESSAGE_TYPE = ERROR_IO_CHANNEL_ERROR_CANT_ACCEPT_INPUT + 1
const ERROR_IO_CHANNEL_READ_WOULD_EXCEED_WINDOW = ERROR_IO_CHANNEL_UNKNOWN_MESSAGE_TYPE + 1
const ERROR_IO_EVENT_LOOP_ALREADY_ASSIGNED = ERROR_IO_CHANNEL_READ_WOULD_EXCEED_WINDOW + 1
const ERROR_IO_EVENT_LOOP_SHUTDOWN = ERROR_IO_EVENT_LOOP_ALREADY_ASSIGNED + 1
const ERROR_IO_TLS_ERROR_NEGOTIATION_FAILURE = ERROR_IO_EVENT_LOOP_SHUTDOWN + 1
const ERROR_IO_TLS_ERROR_NOT_NEGOTIATED = ERROR_IO_TLS_ERROR_NEGOTIATION_FAILURE + 1
const ERROR_IO_TLS_ERROR_WRITE_FAILURE = ERROR_IO_TLS_ERROR_NOT_NEGOTIATED + 1
const ERROR_IO_TLS_ERROR_ALERT_RECEIVED = ERROR_IO_TLS_ERROR_WRITE_FAILURE + 1
const ERROR_IO_TLS_CTX_ERROR = ERROR_IO_TLS_ERROR_ALERT_RECEIVED + 1
const ERROR_IO_TLS_VERSION_UNSUPPORTED = ERROR_IO_TLS_CTX_ERROR + 1
const ERROR_IO_TLS_CIPHER_PREF_UNSUPPORTED = ERROR_IO_TLS_VERSION_UNSUPPORTED + 1
const ERROR_IO_MISSING_ALPN_MESSAGE = ERROR_IO_TLS_CIPHER_PREF_UNSUPPORTED + 1
const ERROR_IO_UNHANDLED_ALPN_PROTOCOL_MESSAGE = ERROR_IO_MISSING_ALPN_MESSAGE + 1
const ERROR_IO_FILE_VALIDATION_FAILURE = ERROR_IO_UNHANDLED_ALPN_PROTOCOL_MESSAGE + 1
const ERROR_IO_EVENT_LOOP_THREAD_ONLY = ERROR_IO_FILE_VALIDATION_FAILURE + 1
const ERROR_IO_ALREADY_SUBSCRIBED = ERROR_IO_EVENT_LOOP_THREAD_ONLY + 1
const ERROR_IO_NOT_SUBSCRIBED = ERROR_IO_ALREADY_SUBSCRIBED + 1
const ERROR_IO_OPERATION_CANCELLED = ERROR_IO_NOT_SUBSCRIBED + 1
const ERROR_IO_READ_WOULD_BLOCK = ERROR_IO_OPERATION_CANCELLED + 1
const ERROR_IO_BROKEN_PIPE = ERROR_IO_READ_WOULD_BLOCK + 1
const ERROR_IO_SOCKET_UNSUPPORTED_ADDRESS_FAMILY = ERROR_IO_BROKEN_PIPE + 1
const ERROR_IO_SOCKET_INVALID_OPERATION_FOR_TYPE = ERROR_IO_SOCKET_UNSUPPORTED_ADDRESS_FAMILY + 1
const ERROR_IO_SOCKET_CONNECTION_REFUSED = ERROR_IO_SOCKET_INVALID_OPERATION_FOR_TYPE + 1
const ERROR_IO_SOCKET_TIMEOUT = ERROR_IO_SOCKET_CONNECTION_REFUSED + 1
const ERROR_IO_SOCKET_NO_ROUTE_TO_HOST = ERROR_IO_SOCKET_TIMEOUT + 1
const ERROR_IO_SOCKET_NETWORK_DOWN = ERROR_IO_SOCKET_NO_ROUTE_TO_HOST + 1
const ERROR_IO_SOCKET_CLOSED = ERROR_IO_SOCKET_NETWORK_DOWN + 1
const ERROR_IO_SOCKET_NOT_CONNECTED = ERROR_IO_SOCKET_CLOSED + 1
const ERROR_IO_SOCKET_INVALID_OPTIONS = ERROR_IO_SOCKET_NOT_CONNECTED + 1
const ERROR_IO_SOCKET_ADDRESS_IN_USE = ERROR_IO_SOCKET_INVALID_OPTIONS + 1
const ERROR_IO_SOCKET_INVALID_ADDRESS = ERROR_IO_SOCKET_ADDRESS_IN_USE + 1
const ERROR_IO_SOCKET_ILLEGAL_OPERATION_FOR_STATE = ERROR_IO_SOCKET_INVALID_ADDRESS + 1
const ERROR_IO_SOCKET_CONNECT_ABORTED = ERROR_IO_SOCKET_ILLEGAL_OPERATION_FOR_STATE + 1
const ERROR_IO_DNS_QUERY_FAILED = ERROR_IO_SOCKET_CONNECT_ABORTED + 1
const ERROR_IO_DNS_INVALID_NAME = ERROR_IO_DNS_QUERY_FAILED + 1
const ERROR_IO_DNS_NO_ADDRESS_FOR_HOST = ERROR_IO_DNS_INVALID_NAME + 1
const ERROR_IO_DNS_HOST_REMOVED_FROM_CACHE = ERROR_IO_DNS_NO_ADDRESS_FOR_HOST + 1
const ERROR_IO_STREAM_INVALID_SEEK_POSITION = ERROR_IO_DNS_HOST_REMOVED_FROM_CACHE + 1
const ERROR_IO_STREAM_READ_FAILED = ERROR_IO_STREAM_INVALID_SEEK_POSITION + 1
const ERROR_IO_INVALID_FILE_HANDLE_DEPRECATED = ERROR_IO_STREAM_READ_FAILED + 1
const ERROR_IO_SHARED_LIBRARY_LOAD_FAILURE = ERROR_IO_INVALID_FILE_HANDLE_DEPRECATED + 1
const ERROR_IO_SHARED_LIBRARY_FIND_SYMBOL_FAILURE = ERROR_IO_SHARED_LIBRARY_LOAD_FAILURE + 1
const ERROR_IO_TLS_NEGOTIATION_TIMEOUT = ERROR_IO_SHARED_LIBRARY_FIND_SYMBOL_FAILURE + 1
const ERROR_IO_TLS_ALERT_NOT_GRACEFUL = ERROR_IO_TLS_NEGOTIATION_TIMEOUT + 1
const ERROR_IO_MAX_RETRIES_EXCEEDED = ERROR_IO_TLS_ALERT_NOT_GRACEFUL + 1
const ERROR_IO_RETRY_PERMISSION_DENIED = ERROR_IO_MAX_RETRIES_EXCEEDED + 1
const ERROR_IO_TLS_DIGEST_ALGORITHM_UNSUPPORTED = ERROR_IO_RETRY_PERMISSION_DENIED + 1
const ERROR_IO_TLS_SIGNATURE_ALGORITHM_UNSUPPORTED = ERROR_IO_TLS_DIGEST_ALGORITHM_UNSUPPORTED + 1
const ERROR_IO_PKCS11_VERSION_UNSUPPORTED = ERROR_IO_TLS_SIGNATURE_ALGORITHM_UNSUPPORTED + 1
const ERROR_IO_PKCS11_TOKEN_NOT_FOUND = ERROR_IO_PKCS11_VERSION_UNSUPPORTED + 1
const ERROR_IO_PKCS11_KEY_NOT_FOUND = ERROR_IO_PKCS11_TOKEN_NOT_FOUND + 1
const ERROR_IO_PKCS11_KEY_TYPE_UNSUPPORTED = ERROR_IO_PKCS11_KEY_NOT_FOUND + 1
const ERROR_IO_PKCS11_UNKNOWN_CRYPTOKI_RETURN_VALUE = ERROR_IO_PKCS11_KEY_TYPE_UNSUPPORTED + 1
# PKCS#11 CKR_* error codes
const ERROR_IO_PKCS11_CKR_CANCEL = ERROR_IO_PKCS11_UNKNOWN_CRYPTOKI_RETURN_VALUE + 1
const ERROR_IO_PKCS11_CKR_HOST_MEMORY = ERROR_IO_PKCS11_CKR_CANCEL + 1
const ERROR_IO_PKCS11_CKR_SLOT_ID_INVALID = ERROR_IO_PKCS11_CKR_HOST_MEMORY + 1
const ERROR_IO_PKCS11_CKR_GENERAL_ERROR = ERROR_IO_PKCS11_CKR_SLOT_ID_INVALID + 1
const ERROR_IO_PKCS11_CKR_FUNCTION_FAILED = ERROR_IO_PKCS11_CKR_GENERAL_ERROR + 1
const ERROR_IO_PKCS11_CKR_ARGUMENTS_BAD = ERROR_IO_PKCS11_CKR_FUNCTION_FAILED + 1
const ERROR_IO_PKCS11_CKR_NO_EVENT = ERROR_IO_PKCS11_CKR_ARGUMENTS_BAD + 1
const ERROR_IO_PKCS11_CKR_NEED_TO_CREATE_THREADS = ERROR_IO_PKCS11_CKR_NO_EVENT + 1
const ERROR_IO_PKCS11_CKR_CANT_LOCK = ERROR_IO_PKCS11_CKR_NEED_TO_CREATE_THREADS + 1
const ERROR_IO_PKCS11_CKR_ATTRIBUTE_READ_ONLY = ERROR_IO_PKCS11_CKR_CANT_LOCK + 1
const ERROR_IO_PKCS11_CKR_ATTRIBUTE_SENSITIVE = ERROR_IO_PKCS11_CKR_ATTRIBUTE_READ_ONLY + 1
const ERROR_IO_PKCS11_CKR_ATTRIBUTE_TYPE_INVALID = ERROR_IO_PKCS11_CKR_ATTRIBUTE_SENSITIVE + 1
const ERROR_IO_PKCS11_CKR_ATTRIBUTE_VALUE_INVALID = ERROR_IO_PKCS11_CKR_ATTRIBUTE_TYPE_INVALID + 1
const ERROR_IO_PKCS11_CKR_ACTION_PROHIBITED = ERROR_IO_PKCS11_CKR_ATTRIBUTE_VALUE_INVALID + 1
const ERROR_IO_PKCS11_CKR_DATA_INVALID = ERROR_IO_PKCS11_CKR_ACTION_PROHIBITED + 1
const ERROR_IO_PKCS11_CKR_DATA_LEN_RANGE = ERROR_IO_PKCS11_CKR_DATA_INVALID + 1
const ERROR_IO_PKCS11_CKR_DEVICE_ERROR = ERROR_IO_PKCS11_CKR_DATA_LEN_RANGE + 1
const ERROR_IO_PKCS11_CKR_DEVICE_MEMORY = ERROR_IO_PKCS11_CKR_DEVICE_ERROR + 1
const ERROR_IO_PKCS11_CKR_DEVICE_REMOVED = ERROR_IO_PKCS11_CKR_DEVICE_MEMORY + 1
const ERROR_IO_PKCS11_CKR_ENCRYPTED_DATA_INVALID = ERROR_IO_PKCS11_CKR_DEVICE_REMOVED + 1
const ERROR_IO_PKCS11_CKR_ENCRYPTED_DATA_LEN_RANGE = ERROR_IO_PKCS11_CKR_ENCRYPTED_DATA_INVALID + 1
const ERROR_IO_PKCS11_CKR_FUNCTION_CANCELED = ERROR_IO_PKCS11_CKR_ENCRYPTED_DATA_LEN_RANGE + 1
const ERROR_IO_PKCS11_CKR_FUNCTION_NOT_PARALLEL = ERROR_IO_PKCS11_CKR_FUNCTION_CANCELED + 1
const ERROR_IO_PKCS11_CKR_FUNCTION_NOT_SUPPORTED = ERROR_IO_PKCS11_CKR_FUNCTION_NOT_PARALLEL + 1
const ERROR_IO_PKCS11_CKR_KEY_HANDLE_INVALID = ERROR_IO_PKCS11_CKR_FUNCTION_NOT_SUPPORTED + 1
const ERROR_IO_PKCS11_CKR_KEY_SIZE_RANGE = ERROR_IO_PKCS11_CKR_KEY_HANDLE_INVALID + 1
const ERROR_IO_PKCS11_CKR_KEY_TYPE_INCONSISTENT = ERROR_IO_PKCS11_CKR_KEY_SIZE_RANGE + 1
const ERROR_IO_PKCS11_CKR_KEY_NOT_NEEDED = ERROR_IO_PKCS11_CKR_KEY_TYPE_INCONSISTENT + 1
const ERROR_IO_PKCS11_CKR_KEY_CHANGED = ERROR_IO_PKCS11_CKR_KEY_NOT_NEEDED + 1
const ERROR_IO_PKCS11_CKR_KEY_NEEDED = ERROR_IO_PKCS11_CKR_KEY_CHANGED + 1
const ERROR_IO_PKCS11_CKR_KEY_INDIGESTIBLE = ERROR_IO_PKCS11_CKR_KEY_NEEDED + 1
const ERROR_IO_PKCS11_CKR_KEY_FUNCTION_NOT_PERMITTED = ERROR_IO_PKCS11_CKR_KEY_INDIGESTIBLE + 1
const ERROR_IO_PKCS11_CKR_KEY_NOT_WRAPPABLE = ERROR_IO_PKCS11_CKR_KEY_FUNCTION_NOT_PERMITTED + 1
const ERROR_IO_PKCS11_CKR_KEY_UNEXTRACTABLE = ERROR_IO_PKCS11_CKR_KEY_NOT_WRAPPABLE + 1
const ERROR_IO_PKCS11_CKR_MECHANISM_INVALID = ERROR_IO_PKCS11_CKR_KEY_UNEXTRACTABLE + 1
const ERROR_IO_PKCS11_CKR_MECHANISM_PARAM_INVALID = ERROR_IO_PKCS11_CKR_MECHANISM_INVALID + 1
const ERROR_IO_PKCS11_CKR_OBJECT_HANDLE_INVALID = ERROR_IO_PKCS11_CKR_MECHANISM_PARAM_INVALID + 1
const ERROR_IO_PKCS11_CKR_OPERATION_ACTIVE = ERROR_IO_PKCS11_CKR_OBJECT_HANDLE_INVALID + 1
const ERROR_IO_PKCS11_CKR_OPERATION_NOT_INITIALIZED = ERROR_IO_PKCS11_CKR_OPERATION_ACTIVE + 1
const ERROR_IO_PKCS11_CKR_PIN_INCORRECT = ERROR_IO_PKCS11_CKR_OPERATION_NOT_INITIALIZED + 1
const ERROR_IO_PKCS11_CKR_PIN_INVALID = ERROR_IO_PKCS11_CKR_PIN_INCORRECT + 1
const ERROR_IO_PKCS11_CKR_PIN_LEN_RANGE = ERROR_IO_PKCS11_CKR_PIN_INVALID + 1
const ERROR_IO_PKCS11_CKR_PIN_EXPIRED = ERROR_IO_PKCS11_CKR_PIN_LEN_RANGE + 1
const ERROR_IO_PKCS11_CKR_PIN_LOCKED = ERROR_IO_PKCS11_CKR_PIN_EXPIRED + 1
const ERROR_IO_PKCS11_CKR_SESSION_CLOSED = ERROR_IO_PKCS11_CKR_PIN_LOCKED + 1
const ERROR_IO_PKCS11_CKR_SESSION_COUNT = ERROR_IO_PKCS11_CKR_SESSION_CLOSED + 1
const ERROR_IO_PKCS11_CKR_SESSION_HANDLE_INVALID = ERROR_IO_PKCS11_CKR_SESSION_COUNT + 1
const ERROR_IO_PKCS11_CKR_SESSION_PARALLEL_NOT_SUPPORTED = ERROR_IO_PKCS11_CKR_SESSION_HANDLE_INVALID + 1
const ERROR_IO_PKCS11_CKR_SESSION_READ_ONLY = ERROR_IO_PKCS11_CKR_SESSION_PARALLEL_NOT_SUPPORTED + 1
const ERROR_IO_PKCS11_CKR_SESSION_EXISTS = ERROR_IO_PKCS11_CKR_SESSION_READ_ONLY + 1
const ERROR_IO_PKCS11_CKR_SESSION_READ_ONLY_EXISTS = ERROR_IO_PKCS11_CKR_SESSION_EXISTS + 1
const ERROR_IO_PKCS11_CKR_SESSION_READ_WRITE_SO_EXISTS = ERROR_IO_PKCS11_CKR_SESSION_READ_ONLY_EXISTS + 1
const ERROR_IO_PKCS11_CKR_SIGNATURE_INVALID = ERROR_IO_PKCS11_CKR_SESSION_READ_WRITE_SO_EXISTS + 1
const ERROR_IO_PKCS11_CKR_SIGNATURE_LEN_RANGE = ERROR_IO_PKCS11_CKR_SIGNATURE_INVALID + 1
const ERROR_IO_PKCS11_CKR_TEMPLATE_INCOMPLETE = ERROR_IO_PKCS11_CKR_SIGNATURE_LEN_RANGE + 1
const ERROR_IO_PKCS11_CKR_TEMPLATE_INCONSISTENT = ERROR_IO_PKCS11_CKR_TEMPLATE_INCOMPLETE + 1
const ERROR_IO_PKCS11_CKR_TOKEN_NOT_PRESENT = ERROR_IO_PKCS11_CKR_TEMPLATE_INCONSISTENT + 1
const ERROR_IO_PKCS11_CKR_TOKEN_NOT_RECOGNIZED = ERROR_IO_PKCS11_CKR_TOKEN_NOT_PRESENT + 1
const ERROR_IO_PKCS11_CKR_TOKEN_WRITE_PROTECTED = ERROR_IO_PKCS11_CKR_TOKEN_NOT_RECOGNIZED + 1
const ERROR_IO_PKCS11_CKR_UNWRAPPING_KEY_HANDLE_INVALID = ERROR_IO_PKCS11_CKR_TOKEN_WRITE_PROTECTED + 1
const ERROR_IO_PKCS11_CKR_UNWRAPPING_KEY_SIZE_RANGE = ERROR_IO_PKCS11_CKR_UNWRAPPING_KEY_HANDLE_INVALID + 1
const ERROR_IO_PKCS11_CKR_UNWRAPPING_KEY_TYPE_INCONSISTENT = ERROR_IO_PKCS11_CKR_UNWRAPPING_KEY_SIZE_RANGE + 1
const ERROR_IO_PKCS11_CKR_USER_ALREADY_LOGGED_IN = ERROR_IO_PKCS11_CKR_UNWRAPPING_KEY_TYPE_INCONSISTENT + 1
const ERROR_IO_PKCS11_CKR_USER_NOT_LOGGED_IN = ERROR_IO_PKCS11_CKR_USER_ALREADY_LOGGED_IN + 1
const ERROR_IO_PKCS11_CKR_USER_PIN_NOT_INITIALIZED = ERROR_IO_PKCS11_CKR_USER_NOT_LOGGED_IN + 1
const ERROR_IO_PKCS11_CKR_USER_TYPE_INVALID = ERROR_IO_PKCS11_CKR_USER_PIN_NOT_INITIALIZED + 1
const ERROR_IO_PKCS11_CKR_USER_ANOTHER_ALREADY_LOGGED_IN = ERROR_IO_PKCS11_CKR_USER_TYPE_INVALID + 1
const ERROR_IO_PKCS11_CKR_USER_TOO_MANY_TYPES = ERROR_IO_PKCS11_CKR_USER_ANOTHER_ALREADY_LOGGED_IN + 1
const ERROR_IO_PKCS11_CKR_WRAPPED_KEY_INVALID = ERROR_IO_PKCS11_CKR_USER_TOO_MANY_TYPES + 1
const ERROR_IO_PKCS11_CKR_WRAPPED_KEY_LEN_RANGE = ERROR_IO_PKCS11_CKR_WRAPPED_KEY_INVALID + 1
const ERROR_IO_PKCS11_CKR_WRAPPING_KEY_HANDLE_INVALID = ERROR_IO_PKCS11_CKR_WRAPPED_KEY_LEN_RANGE + 1
const ERROR_IO_PKCS11_CKR_WRAPPING_KEY_SIZE_RANGE = ERROR_IO_PKCS11_CKR_WRAPPING_KEY_HANDLE_INVALID + 1
const ERROR_IO_PKCS11_CKR_WRAPPING_KEY_TYPE_INCONSISTENT = ERROR_IO_PKCS11_CKR_WRAPPING_KEY_SIZE_RANGE + 1
const ERROR_IO_PKCS11_CKR_RANDOM_SEED_NOT_SUPPORTED = ERROR_IO_PKCS11_CKR_WRAPPING_KEY_TYPE_INCONSISTENT + 1
const ERROR_IO_PKCS11_CKR_RANDOM_NO_RNG = ERROR_IO_PKCS11_CKR_RANDOM_SEED_NOT_SUPPORTED + 1
const ERROR_IO_PKCS11_CKR_DOMAIN_PARAMS_INVALID = ERROR_IO_PKCS11_CKR_RANDOM_NO_RNG + 1
const ERROR_IO_PKCS11_CKR_CURVE_NOT_SUPPORTED = ERROR_IO_PKCS11_CKR_DOMAIN_PARAMS_INVALID + 1
const ERROR_IO_PKCS11_CKR_BUFFER_TOO_SMALL = ERROR_IO_PKCS11_CKR_CURVE_NOT_SUPPORTED + 1
const ERROR_IO_PKCS11_CKR_SAVED_STATE_INVALID = ERROR_IO_PKCS11_CKR_BUFFER_TOO_SMALL + 1
const ERROR_IO_PKCS11_CKR_INFORMATION_SENSITIVE = ERROR_IO_PKCS11_CKR_SAVED_STATE_INVALID + 1
const ERROR_IO_PKCS11_CKR_STATE_UNSAVEABLE = ERROR_IO_PKCS11_CKR_INFORMATION_SENSITIVE + 1
const ERROR_IO_PKCS11_CKR_CRYPTOKI_NOT_INITIALIZED = ERROR_IO_PKCS11_CKR_STATE_UNSAVEABLE + 1
const ERROR_IO_PKCS11_CKR_CRYPTOKI_ALREADY_INITIALIZED = ERROR_IO_PKCS11_CKR_CRYPTOKI_NOT_INITIALIZED + 1
const ERROR_IO_PKCS11_CKR_MUTEX_BAD = ERROR_IO_PKCS11_CKR_CRYPTOKI_ALREADY_INITIALIZED + 1
const ERROR_IO_PKCS11_CKR_MUTEX_NOT_LOCKED = ERROR_IO_PKCS11_CKR_MUTEX_BAD + 1
const ERROR_IO_PKCS11_CKR_NEW_PIN_MODE = ERROR_IO_PKCS11_CKR_MUTEX_NOT_LOCKED + 1
const ERROR_IO_PKCS11_CKR_NEXT_OTP = ERROR_IO_PKCS11_CKR_NEW_PIN_MODE + 1
const ERROR_IO_PKCS11_CKR_EXCEEDED_MAX_ITERATIONS = ERROR_IO_PKCS11_CKR_NEXT_OTP + 1
const ERROR_IO_PKCS11_CKR_FIPS_SELF_TEST_FAILED = ERROR_IO_PKCS11_CKR_EXCEEDED_MAX_ITERATIONS + 1
const ERROR_IO_PKCS11_CKR_LIBRARY_LOAD_FAILED = ERROR_IO_PKCS11_CKR_FIPS_SELF_TEST_FAILED + 1
const ERROR_IO_PKCS11_CKR_PIN_TOO_WEAK = ERROR_IO_PKCS11_CKR_LIBRARY_LOAD_FAILED + 1
const ERROR_IO_PKCS11_CKR_PUBLIC_KEY_INVALID = ERROR_IO_PKCS11_CKR_PIN_TOO_WEAK + 1
const ERROR_IO_PKCS11_CKR_FUNCTION_REJECTED = ERROR_IO_PKCS11_CKR_PUBLIC_KEY_INVALID + 1
const ERROR_IO_PKCS11_ENCODING_ERROR = ERROR_IO_PKCS11_CKR_FUNCTION_REJECTED + 1
const ERROR_IO_TLS_ERROR_DEFAULT_TRUST_STORE_NOT_FOUND = ERROR_IO_PKCS11_ENCODING_ERROR + 1
const ERROR_IO_STREAM_SEEK_UNSUPPORTED = ERROR_IO_TLS_ERROR_DEFAULT_TRUST_STORE_NOT_FOUND + 1
const ERROR_IO_TLS_ERROR_READ_FAILURE = ERROR_IO_STREAM_SEEK_UNSUPPORTED + 1
const ERROR_IO_PEM_MALFORMED = ERROR_IO_TLS_ERROR_READ_FAILURE + 1
const ERROR_IO_SOCKET_MISSING_EVENT_LOOP = ERROR_IO_PEM_MALFORMED + 1
const ERROR_IO_TLS_UNKNOWN_ROOT_CERTIFICATE = ERROR_IO_SOCKET_MISSING_EVENT_LOOP + 1
const ERROR_IO_TLS_NO_ROOT_CERTIFICATE_FOUND = ERROR_IO_TLS_UNKNOWN_ROOT_CERTIFICATE + 1
const ERROR_IO_TLS_CERTIFICATE_EXPIRED = ERROR_IO_TLS_NO_ROOT_CERTIFICATE_FOUND + 1
const ERROR_IO_TLS_CERTIFICATE_NOT_YET_VALID = ERROR_IO_TLS_CERTIFICATE_EXPIRED + 1
const ERROR_IO_TLS_BAD_CERTIFICATE = ERROR_IO_TLS_CERTIFICATE_NOT_YET_VALID + 1
const ERROR_IO_TLS_PEER_CERTIFICATE_EXPIRED = ERROR_IO_TLS_BAD_CERTIFICATE + 1
const ERROR_IO_TLS_BAD_PEER_CERTIFICATE = ERROR_IO_TLS_PEER_CERTIFICATE_EXPIRED + 1
const ERROR_IO_TLS_PEER_CERTIFICATE_REVOKED = ERROR_IO_TLS_BAD_PEER_CERTIFICATE + 1
const ERROR_IO_TLS_PEER_CERTIFICATE_UNKNOWN = ERROR_IO_TLS_PEER_CERTIFICATE_REVOKED + 1
const ERROR_IO_TLS_INTERNAL_ERROR = ERROR_IO_TLS_PEER_CERTIFICATE_UNKNOWN + 1
const ERROR_IO_TLS_CLOSED_GRACEFUL = ERROR_IO_TLS_INTERNAL_ERROR + 1
const ERROR_IO_TLS_CLOSED_ABORT = ERROR_IO_TLS_CLOSED_GRACEFUL + 1
const ERROR_IO_TLS_INVALID_CERTIFICATE_CHAIN = ERROR_IO_TLS_CLOSED_ABORT + 1
const ERROR_IO_TLS_HOST_NAME_MISMATCH = ERROR_IO_TLS_INVALID_CERTIFICATE_CHAIN + 1
const ERROR_IO_DNS_QUERY_AGAIN = ERROR_IO_TLS_HOST_NAME_MISMATCH + 1
const ERROR_IO_END_RANGE = ERROR_ENUM_END_RANGE(IO_PACKAGE_ID)

struct ReseauError <: Exception
    code::Int
end

function Base.showerror(io::IO, e::ReseauError)
    info = get(_error_registry, e.code, nothing)
    if info === nothing
        print(io, "ReseauError: unknown error code $(e.code)")
    else
        print(io, "ReseauError: ", string(info.lib_name, ": ", info.literal_name, ", ", info.error_str))
    end
end

function throw_error(code::Int)
    raise_error_private(code)
    throw(ReseauError(code))
end

struct ErrorInfo
    literal_name::String
    error_str::String
    lib_name::String
end

const _error_registry = Dict{Int, ErrorInfo}(
    # Common registry entries
    ERROR_SUCCESS => ErrorInfo("ERROR_SUCCESS", "Success.", "common"),
    ERROR_OOM => ErrorInfo("ERROR_OOM", "Out of memory.", "common"),
    ERROR_NO_SPACE => ErrorInfo("ERROR_NO_SPACE", "Out of space on disk.", "common"),
    ERROR_UNKNOWN => ErrorInfo("ERROR_UNKNOWN", "Unknown error.", "common"),
    ERROR_SHORT_BUFFER => ErrorInfo("ERROR_SHORT_BUFFER", "Buffer is not large enough to hold result.", "common"),
    ERROR_OVERFLOW_DETECTED => ErrorInfo("ERROR_OVERFLOW_DETECTED", "Fixed size value overflow was detected.", "common"),
    ERROR_INVALID_BUFFER_SIZE => ErrorInfo("ERROR_INVALID_BUFFER_SIZE", "Invalid buffer size.", "common"),
    ERROR_THREAD_NO_SUCH_THREAD_ID => ErrorInfo("ERROR_THREAD_NO_SUCH_THREAD_ID", "No such thread ID.", "common"),
    ERROR_COND_VARIABLE_TIMED_OUT => ErrorInfo("ERROR_COND_VARIABLE_TIMED_OUT", "Condition variable wait timed out.", "common"),
    ERROR_CLOCK_FAILURE => ErrorInfo("ERROR_CLOCK_FAILURE", "Clock operation failed.", "common"),
    ERROR_DEST_COPY_TOO_SMALL => ErrorInfo("ERROR_DEST_COPY_TOO_SMALL", "Destination of copy is too small.", "common"),
    ERROR_INVALID_ARGUMENT => ErrorInfo("ERROR_INVALID_ARGUMENT", "An invalid argument was passed to a function.", "common"),
    ERROR_UNIMPLEMENTED => ErrorInfo("ERROR_UNIMPLEMENTED", "A function was called, but is not implemented.", "common"),
    ERROR_INVALID_STATE => ErrorInfo("ERROR_INVALID_STATE", "An invalid state was encountered.", "common"),
    ERROR_STREAM_UNSEEKABLE => ErrorInfo("ERROR_STREAM_UNSEEKABLE", "Stream does not support seek operations.", "common"),
    ERROR_NO_PERMISSION => ErrorInfo("ERROR_NO_PERMISSION", "User does not have permission to perform the requested action.", "common"),
    ERROR_FILE_INVALID_PATH => ErrorInfo("ERROR_FILE_INVALID_PATH", "Invalid file path.", "common"),
    ERROR_MAX_FDS_EXCEEDED => ErrorInfo("ERROR_MAX_FDS_EXCEEDED", "The maximum number of fds has been exceeded.", "common"),
    ERROR_SYS_CALL_FAILURE => ErrorInfo("ERROR_SYS_CALL_FAILURE", "System call failure.", "common"),
    ERROR_STRING_MATCH_NOT_FOUND => ErrorInfo("ERROR_STRING_MATCH_NOT_FOUND", "The specified substring was not present in the input string.", "common"),
    ERROR_INVALID_FILE_HANDLE => ErrorInfo("ERROR_INVALID_FILE_HANDLE", "Invalid file handle.", "common"),
    ERROR_DIRECTORY_NOT_EMPTY => ErrorInfo("ERROR_DIRECTORY_NOT_EMPTY", "An operation on a directory was attempted which is not allowed when the directory is not empty.", "common"),
    ERROR_PLATFORM_NOT_SUPPORTED => ErrorInfo("ERROR_PLATFORM_NOT_SUPPORTED", "Feature not supported on this platform.", "common"),
    ERROR_FILE_OPEN_FAILURE => ErrorInfo("ERROR_FILE_OPEN_FAILURE", "Failed opening file.", "common"),
    ERROR_FILE_READ_FAILURE => ErrorInfo("ERROR_FILE_READ_FAILURE", "Failed reading from file.", "common"),

    # IO+PKCE registry entries
    ERROR_IO_CHANNEL_ERROR_CANT_ACCEPT_INPUT => ErrorInfo("ERROR_IO_CHANNEL_ERROR_CANT_ACCEPT_INPUT", "Channel cannot accept input", "io"),
    ERROR_IO_CHANNEL_UNKNOWN_MESSAGE_TYPE => ErrorInfo("ERROR_IO_CHANNEL_UNKNOWN_MESSAGE_TYPE", "Channel unknown message type", "io"),
    ERROR_IO_CHANNEL_READ_WOULD_EXCEED_WINDOW => ErrorInfo("ERROR_IO_CHANNEL_READ_WOULD_EXCEED_WINDOW", "A channel handler attempted to propagate a read larger than the upstream window", "io"),
    ERROR_IO_EVENT_LOOP_ALREADY_ASSIGNED => ErrorInfo("ERROR_IO_EVENT_LOOP_ALREADY_ASSIGNED", "An attempt was made to assign an io handle to an event loop, but the handle was already assigned.", "io"),
    ERROR_IO_EVENT_LOOP_SHUTDOWN => ErrorInfo("ERROR_IO_EVENT_LOOP_SHUTDOWN", "Event loop has shutdown and a resource was still using it, the resource has been removed from the loop.", "io"),
    ERROR_IO_TLS_ERROR_NEGOTIATION_FAILURE => ErrorInfo("ERROR_IO_TLS_ERROR_NEGOTIATION_FAILURE", "TLS (SSL) negotiation failed", "io"),
    ERROR_IO_TLS_ERROR_NOT_NEGOTIATED => ErrorInfo("ERROR_IO_TLS_ERROR_NOT_NEGOTIATED", "Attempt to read/write, but TLS (SSL) hasn't been negotiated", "io"),
    ERROR_IO_TLS_ERROR_WRITE_FAILURE => ErrorInfo("ERROR_IO_TLS_ERROR_WRITE_FAILURE", "Failed to write to TLS handler", "io"),
    ERROR_IO_TLS_ERROR_ALERT_RECEIVED => ErrorInfo("ERROR_IO_TLS_ERROR_ALERT_RECEIVED", "Fatal TLS Alert was received", "io"),
    ERROR_IO_TLS_CTX_ERROR => ErrorInfo("ERROR_IO_TLS_CTX_ERROR", "Failed to create tls context", "io"),
    ERROR_IO_TLS_VERSION_UNSUPPORTED => ErrorInfo("ERROR_IO_TLS_VERSION_UNSUPPORTED", "A TLS version was specified that is currently not supported. Consider using AWS_IO_TLS_VER_SYS_DEFAULTS,  and when this lib or the operating system is updated, it will automatically be used.", "io"),
    ERROR_IO_TLS_CIPHER_PREF_UNSUPPORTED => ErrorInfo("ERROR_IO_TLS_CIPHER_PREF_UNSUPPORTED", "A TLS Cipher Preference was specified that is currently not supported by the current platform. Consider  using AWS_IO_TLS_CIPHER_SYSTEM_DEFAULT, and when this lib or the operating system is updated, it will automatically be used.", "io"),
    ERROR_IO_MISSING_ALPN_MESSAGE => ErrorInfo("ERROR_IO_MISSING_ALPN_MESSAGE", "An ALPN message was expected but not received", "io"),
    ERROR_IO_UNHANDLED_ALPN_PROTOCOL_MESSAGE => ErrorInfo("ERROR_IO_UNHANDLED_ALPN_PROTOCOL_MESSAGE", "An ALPN message was received but a handler was not created by the user", "io"),
    ERROR_IO_FILE_VALIDATION_FAILURE => ErrorInfo("ERROR_IO_FILE_VALIDATION_FAILURE", "A file was read and the input did not match the expected value", "io"),
    ERROR_IO_EVENT_LOOP_THREAD_ONLY => ErrorInfo("ERROR_IO_EVENT_LOOP_THREAD_ONLY", "Attempt to perform operation that must be run inside the event loop thread", "io"),
    ERROR_IO_ALREADY_SUBSCRIBED => ErrorInfo("ERROR_IO_ALREADY_SUBSCRIBED", "Already subscribed to receive events", "io"),
    ERROR_IO_NOT_SUBSCRIBED => ErrorInfo("ERROR_IO_NOT_SUBSCRIBED", "Not subscribed to receive events", "io"),
    ERROR_IO_OPERATION_CANCELLED => ErrorInfo("ERROR_IO_OPERATION_CANCELLED", "Operation cancelled before it could complete", "io"),
    ERROR_IO_READ_WOULD_BLOCK => ErrorInfo("ERROR_IO_READ_WOULD_BLOCK", "Read operation would block, try again later", "io"),
    ERROR_IO_BROKEN_PIPE => ErrorInfo("ERROR_IO_BROKEN_PIPE", "Attempt to read or write to io handle that has already been closed.", "io"),
    ERROR_IO_SOCKET_UNSUPPORTED_ADDRESS_FAMILY => ErrorInfo("ERROR_IO_SOCKET_UNSUPPORTED_ADDRESS_FAMILY", "Socket, unsupported address family.", "io"),
    ERROR_IO_SOCKET_INVALID_OPERATION_FOR_TYPE => ErrorInfo("ERROR_IO_SOCKET_INVALID_OPERATION_FOR_TYPE", "Invalid socket operation for socket type.", "io"),
    ERROR_IO_SOCKET_CONNECTION_REFUSED => ErrorInfo("ERROR_IO_SOCKET_CONNECTION_REFUSED", "socket connection refused.", "io"),
    ERROR_IO_SOCKET_TIMEOUT => ErrorInfo("ERROR_IO_SOCKET_TIMEOUT", "socket operation timed out.", "io"),
    ERROR_IO_SOCKET_NO_ROUTE_TO_HOST => ErrorInfo("ERROR_IO_SOCKET_NO_ROUTE_TO_HOST", "socket connect failure, no route to host.", "io"),
    ERROR_IO_SOCKET_NETWORK_DOWN => ErrorInfo("ERROR_IO_SOCKET_NETWORK_DOWN", "network is down.", "io"),
    ERROR_IO_SOCKET_CLOSED => ErrorInfo("ERROR_IO_SOCKET_CLOSED", "socket is closed.", "io"),
    ERROR_IO_SOCKET_NOT_CONNECTED => ErrorInfo("ERROR_IO_SOCKET_NOT_CONNECTED", "socket not connected.", "io"),
    ERROR_IO_SOCKET_INVALID_OPTIONS => ErrorInfo("ERROR_IO_SOCKET_INVALID_OPTIONS", "Invalid socket options.", "io"),
    ERROR_IO_SOCKET_ADDRESS_IN_USE => ErrorInfo("ERROR_IO_SOCKET_ADDRESS_IN_USE", "Socket address already in use.", "io"),
    ERROR_IO_SOCKET_INVALID_ADDRESS => ErrorInfo("ERROR_IO_SOCKET_INVALID_ADDRESS", "Invalid socket address.", "io"),
    ERROR_IO_SOCKET_ILLEGAL_OPERATION_FOR_STATE => ErrorInfo("ERROR_IO_SOCKET_ILLEGAL_OPERATION_FOR_STATE", "Illegal operation for socket state.", "io"),
    ERROR_IO_SOCKET_CONNECT_ABORTED => ErrorInfo("ERROR_IO_SOCKET_CONNECT_ABORTED", "Incoming connection was aborted.", "io"),
    ERROR_IO_DNS_QUERY_FAILED => ErrorInfo("ERROR_IO_DNS_QUERY_FAILED", "A nonrecoverable failure when query to dns occurred.", "io"),
    ERROR_IO_DNS_INVALID_NAME => ErrorInfo("ERROR_IO_DNS_INVALID_NAME", "Host name was invalid for dns resolution.", "io"),
    ERROR_IO_DNS_NO_ADDRESS_FOR_HOST => ErrorInfo("ERROR_IO_DNS_NO_ADDRESS_FOR_HOST", "No address was found for the supplied host name.", "io"),
    ERROR_IO_DNS_HOST_REMOVED_FROM_CACHE => ErrorInfo("ERROR_IO_DNS_HOST_REMOVED_FROM_CACHE", "The entries for host name were removed from the local dns cache.", "io"),
    ERROR_IO_STREAM_INVALID_SEEK_POSITION => ErrorInfo("ERROR_IO_STREAM_INVALID_SEEK_POSITION", "The seek position was outside of a stream's bounds", "io"),
    ERROR_IO_STREAM_READ_FAILED => ErrorInfo("ERROR_IO_STREAM_READ_FAILED", "Stream failed to read from the underlying io source", "io"),
    ERROR_IO_INVALID_FILE_HANDLE_DEPRECATED => ErrorInfo("ERROR_IO_INVALID_FILE_HANDLE_DEPRECATED", "Operation failed because the file handle was invalid", "io"),
    ERROR_IO_SHARED_LIBRARY_LOAD_FAILURE => ErrorInfo("ERROR_IO_SHARED_LIBRARY_LOAD_FAILURE", "System call error during attempt to load shared library", "io"),
    ERROR_IO_SHARED_LIBRARY_FIND_SYMBOL_FAILURE => ErrorInfo("ERROR_IO_SHARED_LIBRARY_FIND_SYMBOL_FAILURE", "System call error during attempt to find shared library symbol", "io"),
    ERROR_IO_TLS_NEGOTIATION_TIMEOUT => ErrorInfo("ERROR_IO_TLS_NEGOTIATION_TIMEOUT", "Channel shutdown due to tls negotiation timeout", "io"),
    ERROR_IO_TLS_ALERT_NOT_GRACEFUL => ErrorInfo("ERROR_IO_TLS_ALERT_NOT_GRACEFUL", "Channel shutdown due to tls alert. The alert was not for a graceful shutdown.", "io"),
    ERROR_IO_MAX_RETRIES_EXCEEDED => ErrorInfo("ERROR_IO_MAX_RETRIES_EXCEEDED", "Retry cannot be attempted because the maximum number of retries has been exceeded.", "io"),
    ERROR_IO_RETRY_PERMISSION_DENIED => ErrorInfo("ERROR_IO_RETRY_PERMISSION_DENIED", "Retry cannot be attempted because the retry strategy has prevented the operation.", "io"),
    ERROR_IO_TLS_DIGEST_ALGORITHM_UNSUPPORTED => ErrorInfo("ERROR_IO_TLS_DIGEST_ALGORITHM_UNSUPPORTED", "TLS digest was created with an unsupported algorithm", "io"),
    ERROR_IO_TLS_SIGNATURE_ALGORITHM_UNSUPPORTED => ErrorInfo("ERROR_IO_TLS_SIGNATURE_ALGORITHM_UNSUPPORTED", "TLS signature algorithm is currently unsupported.", "io"),
    ERROR_IO_PKCS11_VERSION_UNSUPPORTED => ErrorInfo("ERROR_IO_PKCS11_VERSION_UNSUPPORTED", "The PKCS#11 library uses an unsupported API version.", "io"),
    ERROR_IO_PKCS11_TOKEN_NOT_FOUND => ErrorInfo("ERROR_IO_PKCS11_TOKEN_NOT_FOUND", "Could not pick PKCS#11 token matching search criteria (none found, or multiple found)", "io"),
    ERROR_IO_PKCS11_KEY_NOT_FOUND => ErrorInfo("ERROR_IO_PKCS11_KEY_NOT_FOUND", "Could not pick PKCS#11 key matching search criteria (none found, or multiple found)", "io"),
    ERROR_IO_PKCS11_KEY_TYPE_UNSUPPORTED => ErrorInfo("ERROR_IO_PKCS11_KEY_TYPE_UNSUPPORTED", "PKCS#11 key type not supported", "io"),
    ERROR_IO_PKCS11_UNKNOWN_CRYPTOKI_RETURN_VALUE => ErrorInfo("ERROR_IO_PKCS11_UNKNOWN_CRYPTOKI_RETURN_VALUE", "A PKCS#11 (Cryptoki) library function failed with an unknown return value (CKR_). See log for more details.", "io"),
    ERROR_IO_PKCS11_CKR_CANCEL => ErrorInfo("ERROR_IO_PKCS11_CKR_CANCEL", "A PKCS#11 (Cryptoki) library function failed with return value CKR_CANCEL", "pkce"),
    ERROR_IO_PKCS11_CKR_HOST_MEMORY => ErrorInfo("ERROR_IO_PKCS11_CKR_HOST_MEMORY", "A PKCS#11 (Cryptoki) library function failed with return value CKR_HOST_MEMORY", "pkce"),
    ERROR_IO_PKCS11_CKR_SLOT_ID_INVALID => ErrorInfo("ERROR_IO_PKCS11_CKR_SLOT_ID_INVALID", "A PKCS#11 (Cryptoki) library function failed with return value CKR_SLOT_ID_INVALID", "pkce"),
    ERROR_IO_PKCS11_CKR_GENERAL_ERROR => ErrorInfo("ERROR_IO_PKCS11_CKR_GENERAL_ERROR", "A PKCS#11 (Cryptoki) library function failed with return value CKR_GENERAL_ERROR", "pkce"),
    ERROR_IO_PKCS11_CKR_FUNCTION_FAILED => ErrorInfo("ERROR_IO_PKCS11_CKR_FUNCTION_FAILED", "A PKCS#11 (Cryptoki) library function failed with return value CKR_FUNCTION_FAILED", "pkce"),
    ERROR_IO_PKCS11_CKR_ARGUMENTS_BAD => ErrorInfo("ERROR_IO_PKCS11_CKR_ARGUMENTS_BAD", "A PKCS#11 (Cryptoki) library function failed with return value CKR_ARGUMENTS_BAD", "pkce"),
    ERROR_IO_PKCS11_CKR_NO_EVENT => ErrorInfo("ERROR_IO_PKCS11_CKR_NO_EVENT", "A PKCS#11 (Cryptoki) library function failed with return value CKR_NO_EVENT", "pkce"),
    ERROR_IO_PKCS11_CKR_NEED_TO_CREATE_THREADS => ErrorInfo("ERROR_IO_PKCS11_CKR_NEED_TO_CREATE_THREADS", "A PKCS#11 (Cryptoki) library function failed with return value CKR_NEED_TO_CREATE_THREADS", "pkce"),
    ERROR_IO_PKCS11_CKR_CANT_LOCK => ErrorInfo("ERROR_IO_PKCS11_CKR_CANT_LOCK", "A PKCS#11 (Cryptoki) library function failed with return value CKR_CANT_LOCK", "pkce"),
    ERROR_IO_PKCS11_CKR_ATTRIBUTE_READ_ONLY => ErrorInfo("ERROR_IO_PKCS11_CKR_ATTRIBUTE_READ_ONLY", "A PKCS#11 (Cryptoki) library function failed with return value CKR_ATTRIBUTE_READ_ONLY", "pkce"),
    ERROR_IO_PKCS11_CKR_ATTRIBUTE_SENSITIVE => ErrorInfo("ERROR_IO_PKCS11_CKR_ATTRIBUTE_SENSITIVE", "A PKCS#11 (Cryptoki) library function failed with return value CKR_ATTRIBUTE_SENSITIVE", "pkce"),
    ERROR_IO_PKCS11_CKR_ATTRIBUTE_TYPE_INVALID => ErrorInfo("ERROR_IO_PKCS11_CKR_ATTRIBUTE_TYPE_INVALID", "A PKCS#11 (Cryptoki) library function failed with return value CKR_ATTRIBUTE_TYPE_INVALID", "pkce"),
    ERROR_IO_PKCS11_CKR_ATTRIBUTE_VALUE_INVALID => ErrorInfo("ERROR_IO_PKCS11_CKR_ATTRIBUTE_VALUE_INVALID", "A PKCS#11 (Cryptoki) library function failed with return value CKR_ATTRIBUTE_VALUE_INVALID", "pkce"),
    ERROR_IO_PKCS11_CKR_ACTION_PROHIBITED => ErrorInfo("ERROR_IO_PKCS11_CKR_ACTION_PROHIBITED", "A PKCS#11 (Cryptoki) library function failed with return value CKR_ACTION_PROHIBITED", "pkce"),
    ERROR_IO_PKCS11_CKR_DATA_INVALID => ErrorInfo("ERROR_IO_PKCS11_CKR_DATA_INVALID", "A PKCS#11 (Cryptoki) library function failed with return value CKR_DATA_INVALID", "pkce"),
    ERROR_IO_PKCS11_CKR_DATA_LEN_RANGE => ErrorInfo("ERROR_IO_PKCS11_CKR_DATA_LEN_RANGE", "A PKCS#11 (Cryptoki) library function failed with return value CKR_DATA_LEN_RANGE", "pkce"),
    ERROR_IO_PKCS11_CKR_DEVICE_ERROR => ErrorInfo("ERROR_IO_PKCS11_CKR_DEVICE_ERROR", "A PKCS#11 (Cryptoki) library function failed with return value CKR_DEVICE_ERROR", "pkce"),
    ERROR_IO_PKCS11_CKR_DEVICE_MEMORY => ErrorInfo("ERROR_IO_PKCS11_CKR_DEVICE_MEMORY", "A PKCS#11 (Cryptoki) library function failed with return value CKR_DEVICE_MEMORY", "pkce"),
    ERROR_IO_PKCS11_CKR_DEVICE_REMOVED => ErrorInfo("ERROR_IO_PKCS11_CKR_DEVICE_REMOVED", "A PKCS#11 (Cryptoki) library function failed with return value CKR_DEVICE_REMOVED", "pkce"),
    ERROR_IO_PKCS11_CKR_ENCRYPTED_DATA_INVALID => ErrorInfo("ERROR_IO_PKCS11_CKR_ENCRYPTED_DATA_INVALID", "A PKCS#11 (Cryptoki) library function failed with return value CKR_ENCRYPTED_DATA_INVALID", "pkce"),
    ERROR_IO_PKCS11_CKR_ENCRYPTED_DATA_LEN_RANGE => ErrorInfo("ERROR_IO_PKCS11_CKR_ENCRYPTED_DATA_LEN_RANGE", "A PKCS#11 (Cryptoki) library function failed with return value CKR_ENCRYPTED_DATA_LEN_RANGE", "pkce"),
    ERROR_IO_PKCS11_CKR_FUNCTION_CANCELED => ErrorInfo("ERROR_IO_PKCS11_CKR_FUNCTION_CANCELED", "A PKCS#11 (Cryptoki) library function failed with return value CKR_FUNCTION_CANCELED", "pkce"),
    ERROR_IO_PKCS11_CKR_FUNCTION_NOT_PARALLEL => ErrorInfo("ERROR_IO_PKCS11_CKR_FUNCTION_NOT_PARALLEL", "A PKCS#11 (Cryptoki) library function failed with return value CKR_FUNCTION_NOT_PARALLEL", "pkce"),
    ERROR_IO_PKCS11_CKR_FUNCTION_NOT_SUPPORTED => ErrorInfo("ERROR_IO_PKCS11_CKR_FUNCTION_NOT_SUPPORTED", "A PKCS#11 (Cryptoki) library function failed with return value CKR_FUNCTION_NOT_SUPPORTED", "pkce"),
    ERROR_IO_PKCS11_CKR_KEY_HANDLE_INVALID => ErrorInfo("ERROR_IO_PKCS11_CKR_KEY_HANDLE_INVALID", "A PKCS#11 (Cryptoki) library function failed with return value CKR_KEY_HANDLE_INVALID", "pkce"),
    ERROR_IO_PKCS11_CKR_KEY_SIZE_RANGE => ErrorInfo("ERROR_IO_PKCS11_CKR_KEY_SIZE_RANGE", "A PKCS#11 (Cryptoki) library function failed with return value CKR_KEY_SIZE_RANGE", "pkce"),
    ERROR_IO_PKCS11_CKR_KEY_TYPE_INCONSISTENT => ErrorInfo("ERROR_IO_PKCS11_CKR_KEY_TYPE_INCONSISTENT", "A PKCS#11 (Cryptoki) library function failed with return value CKR_KEY_TYPE_INCONSISTENT", "pkce"),
    ERROR_IO_PKCS11_CKR_KEY_NOT_NEEDED => ErrorInfo("ERROR_IO_PKCS11_CKR_KEY_NOT_NEEDED", "A PKCS#11 (Cryptoki) library function failed with return value CKR_KEY_NOT_NEEDED", "pkce"),
    ERROR_IO_PKCS11_CKR_KEY_CHANGED => ErrorInfo("ERROR_IO_PKCS11_CKR_KEY_CHANGED", "A PKCS#11 (Cryptoki) library function failed with return value CKR_KEY_CHANGED", "pkce"),
    ERROR_IO_PKCS11_CKR_KEY_NEEDED => ErrorInfo("ERROR_IO_PKCS11_CKR_KEY_NEEDED", "A PKCS#11 (Cryptoki) library function failed with return value CKR_KEY_NEEDED", "pkce"),
    ERROR_IO_PKCS11_CKR_KEY_INDIGESTIBLE => ErrorInfo("ERROR_IO_PKCS11_CKR_KEY_INDIGESTIBLE", "A PKCS#11 (Cryptoki) library function failed with return value CKR_KEY_INDIGESTIBLE", "pkce"),
    ERROR_IO_PKCS11_CKR_KEY_FUNCTION_NOT_PERMITTED => ErrorInfo("ERROR_IO_PKCS11_CKR_KEY_FUNCTION_NOT_PERMITTED", "A PKCS#11 (Cryptoki) library function failed with return value CKR_KEY_FUNCTION_NOT_PERMITTED", "pkce"),
    ERROR_IO_PKCS11_CKR_KEY_NOT_WRAPPABLE => ErrorInfo("ERROR_IO_PKCS11_CKR_KEY_NOT_WRAPPABLE", "A PKCS#11 (Cryptoki) library function failed with return value CKR_KEY_NOT_WRAPPABLE", "pkce"),
    ERROR_IO_PKCS11_CKR_KEY_UNEXTRACTABLE => ErrorInfo("ERROR_IO_PKCS11_CKR_KEY_UNEXTRACTABLE", "A PKCS#11 (Cryptoki) library function failed with return value CKR_KEY_UNEXTRACTABLE", "pkce"),
    ERROR_IO_PKCS11_CKR_MECHANISM_INVALID => ErrorInfo("ERROR_IO_PKCS11_CKR_MECHANISM_INVALID", "A PKCS#11 (Cryptoki) library function failed with return value CKR_MECHANISM_INVALID", "pkce"),
    ERROR_IO_PKCS11_CKR_MECHANISM_PARAM_INVALID => ErrorInfo("ERROR_IO_PKCS11_CKR_MECHANISM_PARAM_INVALID", "A PKCS#11 (Cryptoki) library function failed with return value CKR_MECHANISM_PARAM_INVALID", "pkce"),
    ERROR_IO_PKCS11_CKR_OBJECT_HANDLE_INVALID => ErrorInfo("ERROR_IO_PKCS11_CKR_OBJECT_HANDLE_INVALID", "A PKCS#11 (Cryptoki) library function failed with return value CKR_OBJECT_HANDLE_INVALID", "pkce"),
    ERROR_IO_PKCS11_CKR_OPERATION_ACTIVE => ErrorInfo("ERROR_IO_PKCS11_CKR_OPERATION_ACTIVE", "A PKCS#11 (Cryptoki) library function failed with return value CKR_OPERATION_ACTIVE", "pkce"),
    ERROR_IO_PKCS11_CKR_OPERATION_NOT_INITIALIZED => ErrorInfo("ERROR_IO_PKCS11_CKR_OPERATION_NOT_INITIALIZED", "A PKCS#11 (Cryptoki) library function failed with return value CKR_OPERATION_NOT_INITIALIZED", "pkce"),
    ERROR_IO_PKCS11_CKR_PIN_INCORRECT => ErrorInfo("ERROR_IO_PKCS11_CKR_PIN_INCORRECT", "A PKCS#11 (Cryptoki) library function failed with return value CKR_PIN_INCORRECT", "pkce"),
    ERROR_IO_PKCS11_CKR_PIN_INVALID => ErrorInfo("ERROR_IO_PKCS11_CKR_PIN_INVALID", "A PKCS#11 (Cryptoki) library function failed with return value CKR_PIN_INVALID", "pkce"),
    ERROR_IO_PKCS11_CKR_PIN_LEN_RANGE => ErrorInfo("ERROR_IO_PKCS11_CKR_PIN_LEN_RANGE", "A PKCS#11 (Cryptoki) library function failed with return value CKR_PIN_LEN_RANGE", "pkce"),
    ERROR_IO_PKCS11_CKR_PIN_EXPIRED => ErrorInfo("ERROR_IO_PKCS11_CKR_PIN_EXPIRED", "A PKCS#11 (Cryptoki) library function failed with return value CKR_PIN_EXPIRED", "pkce"),
    ERROR_IO_PKCS11_CKR_PIN_LOCKED => ErrorInfo("ERROR_IO_PKCS11_CKR_PIN_LOCKED", "A PKCS#11 (Cryptoki) library function failed with return value CKR_PIN_LOCKED", "pkce"),
    ERROR_IO_PKCS11_CKR_SESSION_CLOSED => ErrorInfo("ERROR_IO_PKCS11_CKR_SESSION_CLOSED", "A PKCS#11 (Cryptoki) library function failed with return value CKR_SESSION_CLOSED", "pkce"),
    ERROR_IO_PKCS11_CKR_SESSION_COUNT => ErrorInfo("ERROR_IO_PKCS11_CKR_SESSION_COUNT", "A PKCS#11 (Cryptoki) library function failed with return value CKR_SESSION_COUNT", "pkce"),
    ERROR_IO_PKCS11_CKR_SESSION_HANDLE_INVALID => ErrorInfo("ERROR_IO_PKCS11_CKR_SESSION_HANDLE_INVALID", "A PKCS#11 (Cryptoki) library function failed with return value CKR_SESSION_HANDLE_INVALID", "pkce"),
    ERROR_IO_PKCS11_CKR_SESSION_PARALLEL_NOT_SUPPORTED => ErrorInfo("ERROR_IO_PKCS11_CKR_SESSION_PARALLEL_NOT_SUPPORTED", "A PKCS#11 (Cryptoki) library function failed with return value CKR_SESSION_PARALLEL_NOT_SUPPORTED", "pkce"),
    ERROR_IO_PKCS11_CKR_SESSION_READ_ONLY => ErrorInfo("ERROR_IO_PKCS11_CKR_SESSION_READ_ONLY", "A PKCS#11 (Cryptoki) library function failed with return value CKR_SESSION_READ_ONLY", "pkce"),
    ERROR_IO_PKCS11_CKR_SESSION_EXISTS => ErrorInfo("ERROR_IO_PKCS11_CKR_SESSION_EXISTS", "A PKCS#11 (Cryptoki) library function failed with return value CKR_SESSION_EXISTS", "pkce"),
    ERROR_IO_PKCS11_CKR_SESSION_READ_ONLY_EXISTS => ErrorInfo("ERROR_IO_PKCS11_CKR_SESSION_READ_ONLY_EXISTS", "A PKCS#11 (Cryptoki) library function failed with return value CKR_SESSION_READ_ONLY_EXISTS", "pkce"),
    ERROR_IO_PKCS11_CKR_SESSION_READ_WRITE_SO_EXISTS => ErrorInfo("ERROR_IO_PKCS11_CKR_SESSION_READ_WRITE_SO_EXISTS", "A PKCS#11 (Cryptoki) library function failed with return value CKR_SESSION_READ_WRITE_SO_EXISTS", "pkce"),
    ERROR_IO_PKCS11_CKR_SIGNATURE_INVALID => ErrorInfo("ERROR_IO_PKCS11_CKR_SIGNATURE_INVALID", "A PKCS#11 (Cryptoki) library function failed with return value CKR_SIGNATURE_INVALID", "pkce"),
    ERROR_IO_PKCS11_CKR_SIGNATURE_LEN_RANGE => ErrorInfo("ERROR_IO_PKCS11_CKR_SIGNATURE_LEN_RANGE", "A PKCS#11 (Cryptoki) library function failed with return value CKR_SIGNATURE_LEN_RANGE", "pkce"),
    ERROR_IO_PKCS11_CKR_TEMPLATE_INCOMPLETE => ErrorInfo("ERROR_IO_PKCS11_CKR_TEMPLATE_INCOMPLETE", "A PKCS#11 (Cryptoki) library function failed with return value CKR_TEMPLATE_INCOMPLETE", "pkce"),
    ERROR_IO_PKCS11_CKR_TEMPLATE_INCONSISTENT => ErrorInfo("ERROR_IO_PKCS11_CKR_TEMPLATE_INCONSISTENT", "A PKCS#11 (Cryptoki) library function failed with return value CKR_TEMPLATE_INCONSISTENT", "pkce"),
    ERROR_IO_PKCS11_CKR_TOKEN_NOT_PRESENT => ErrorInfo("ERROR_IO_PKCS11_CKR_TOKEN_NOT_PRESENT", "A PKCS#11 (Cryptoki) library function failed with return value CKR_TOKEN_NOT_PRESENT", "pkce"),
    ERROR_IO_PKCS11_CKR_TOKEN_NOT_RECOGNIZED => ErrorInfo("ERROR_IO_PKCS11_CKR_TOKEN_NOT_RECOGNIZED", "A PKCS#11 (Cryptoki) library function failed with return value CKR_TOKEN_NOT_RECOGNIZED", "pkce"),
    ERROR_IO_PKCS11_CKR_TOKEN_WRITE_PROTECTED => ErrorInfo("ERROR_IO_PKCS11_CKR_TOKEN_WRITE_PROTECTED", "A PKCS#11 (Cryptoki) library function failed with return value CKR_TOKEN_WRITE_PROTECTED", "pkce"),
    ERROR_IO_PKCS11_CKR_UNWRAPPING_KEY_HANDLE_INVALID => ErrorInfo("ERROR_IO_PKCS11_CKR_UNWRAPPING_KEY_HANDLE_INVALID", "A PKCS#11 (Cryptoki) library function failed with return value CKR_UNWRAPPING_KEY_HANDLE_INVALID", "pkce"),
    ERROR_IO_PKCS11_CKR_UNWRAPPING_KEY_SIZE_RANGE => ErrorInfo("ERROR_IO_PKCS11_CKR_UNWRAPPING_KEY_SIZE_RANGE", "A PKCS#11 (Cryptoki) library function failed with return value CKR_UNWRAPPING_KEY_SIZE_RANGE", "pkce"),
    ERROR_IO_PKCS11_CKR_UNWRAPPING_KEY_TYPE_INCONSISTENT => ErrorInfo("ERROR_IO_PKCS11_CKR_UNWRAPPING_KEY_TYPE_INCONSISTENT", "A PKCS#11 (Cryptoki) library function failed with return value CKR_UNWRAPPING_KEY_TYPE_INCONSISTENT", "pkce"),
    ERROR_IO_PKCS11_CKR_USER_ALREADY_LOGGED_IN => ErrorInfo("ERROR_IO_PKCS11_CKR_USER_ALREADY_LOGGED_IN", "A PKCS#11 (Cryptoki) library function failed with return value CKR_USER_ALREADY_LOGGED_IN", "pkce"),
    ERROR_IO_PKCS11_CKR_USER_NOT_LOGGED_IN => ErrorInfo("ERROR_IO_PKCS11_CKR_USER_NOT_LOGGED_IN", "A PKCS#11 (Cryptoki) library function failed with return value CKR_USER_NOT_LOGGED_IN", "pkce"),
    ERROR_IO_PKCS11_CKR_USER_PIN_NOT_INITIALIZED => ErrorInfo("ERROR_IO_PKCS11_CKR_USER_PIN_NOT_INITIALIZED", "A PKCS#11 (Cryptoki) library function failed with return value CKR_USER_PIN_NOT_INITIALIZED", "pkce"),
    ERROR_IO_PKCS11_CKR_USER_TYPE_INVALID => ErrorInfo("ERROR_IO_PKCS11_CKR_USER_TYPE_INVALID", "A PKCS#11 (Cryptoki) library function failed with return value CKR_USER_TYPE_INVALID", "pkce"),
    ERROR_IO_PKCS11_CKR_USER_ANOTHER_ALREADY_LOGGED_IN => ErrorInfo("ERROR_IO_PKCS11_CKR_USER_ANOTHER_ALREADY_LOGGED_IN", "A PKCS#11 (Cryptoki) library function failed with return value CKR_USER_ANOTHER_ALREADY_LOGGED_IN", "pkce"),
    ERROR_IO_PKCS11_CKR_USER_TOO_MANY_TYPES => ErrorInfo("ERROR_IO_PKCS11_CKR_USER_TOO_MANY_TYPES", "A PKCS#11 (Cryptoki) library function failed with return value CKR_USER_TOO_MANY_TYPES", "pkce"),
    ERROR_IO_PKCS11_CKR_WRAPPED_KEY_INVALID => ErrorInfo("ERROR_IO_PKCS11_CKR_WRAPPED_KEY_INVALID", "A PKCS#11 (Cryptoki) library function failed with return value CKR_WRAPPED_KEY_INVALID", "pkce"),
    ERROR_IO_PKCS11_CKR_WRAPPED_KEY_LEN_RANGE => ErrorInfo("ERROR_IO_PKCS11_CKR_WRAPPED_KEY_LEN_RANGE", "A PKCS#11 (Cryptoki) library function failed with return value CKR_WRAPPED_KEY_LEN_RANGE", "pkce"),
    ERROR_IO_PKCS11_CKR_WRAPPING_KEY_HANDLE_INVALID => ErrorInfo("ERROR_IO_PKCS11_CKR_WRAPPING_KEY_HANDLE_INVALID", "A PKCS#11 (Cryptoki) library function failed with return value CKR_WRAPPING_KEY_HANDLE_INVALID", "pkce"),
    ERROR_IO_PKCS11_CKR_WRAPPING_KEY_SIZE_RANGE => ErrorInfo("ERROR_IO_PKCS11_CKR_WRAPPING_KEY_SIZE_RANGE", "A PKCS#11 (Cryptoki) library function failed with return value CKR_WRAPPING_KEY_SIZE_RANGE", "pkce"),
    ERROR_IO_PKCS11_CKR_WRAPPING_KEY_TYPE_INCONSISTENT => ErrorInfo("ERROR_IO_PKCS11_CKR_WRAPPING_KEY_TYPE_INCONSISTENT", "A PKCS#11 (Cryptoki) library function failed with return value CKR_WRAPPING_KEY_TYPE_INCONSISTENT", "pkce"),
    ERROR_IO_PKCS11_CKR_RANDOM_SEED_NOT_SUPPORTED => ErrorInfo("ERROR_IO_PKCS11_CKR_RANDOM_SEED_NOT_SUPPORTED", "A PKCS#11 (Cryptoki) library function failed with return value CKR_RANDOM_SEED_NOT_SUPPORTED", "pkce"),
    ERROR_IO_PKCS11_CKR_RANDOM_NO_RNG => ErrorInfo("ERROR_IO_PKCS11_CKR_RANDOM_NO_RNG", "A PKCS#11 (Cryptoki) library function failed with return value CKR_RANDOM_NO_RNG", "pkce"),
    ERROR_IO_PKCS11_CKR_DOMAIN_PARAMS_INVALID => ErrorInfo("ERROR_IO_PKCS11_CKR_DOMAIN_PARAMS_INVALID", "A PKCS#11 (Cryptoki) library function failed with return value CKR_DOMAIN_PARAMS_INVALID", "pkce"),
    ERROR_IO_PKCS11_CKR_CURVE_NOT_SUPPORTED => ErrorInfo("ERROR_IO_PKCS11_CKR_CURVE_NOT_SUPPORTED", "A PKCS#11 (Cryptoki) library function failed with return value CKR_CURVE_NOT_SUPPORTED", "pkce"),
    ERROR_IO_PKCS11_CKR_BUFFER_TOO_SMALL => ErrorInfo("ERROR_IO_PKCS11_CKR_BUFFER_TOO_SMALL", "A PKCS#11 (Cryptoki) library function failed with return value CKR_BUFFER_TOO_SMALL", "pkce"),
    ERROR_IO_PKCS11_CKR_SAVED_STATE_INVALID => ErrorInfo("ERROR_IO_PKCS11_CKR_SAVED_STATE_INVALID", "A PKCS#11 (Cryptoki) library function failed with return value CKR_SAVED_STATE_INVALID", "pkce"),
    ERROR_IO_PKCS11_CKR_INFORMATION_SENSITIVE => ErrorInfo("ERROR_IO_PKCS11_CKR_INFORMATION_SENSITIVE", "A PKCS#11 (Cryptoki) library function failed with return value CKR_INFORMATION_SENSITIVE", "pkce"),
    ERROR_IO_PKCS11_CKR_STATE_UNSAVEABLE => ErrorInfo("ERROR_IO_PKCS11_CKR_STATE_UNSAVEABLE", "A PKCS#11 (Cryptoki) library function failed with return value CKR_STATE_UNSAVEABLE", "pkce"),
    ERROR_IO_PKCS11_CKR_CRYPTOKI_NOT_INITIALIZED => ErrorInfo("ERROR_IO_PKCS11_CKR_CRYPTOKI_NOT_INITIALIZED", "A PKCS#11 (Cryptoki) library function failed with return value CKR_CRYPTOKI_NOT_INITIALIZED", "pkce"),
    ERROR_IO_PKCS11_CKR_CRYPTOKI_ALREADY_INITIALIZED => ErrorInfo("ERROR_IO_PKCS11_CKR_CRYPTOKI_ALREADY_INITIALIZED", "A PKCS#11 (Cryptoki) library function failed with return value CKR_CRYPTOKI_ALREADY_INITIALIZED", "pkce"),
    ERROR_IO_PKCS11_CKR_MUTEX_BAD => ErrorInfo("ERROR_IO_PKCS11_CKR_MUTEX_BAD", "A PKCS#11 (Cryptoki) library function failed with return value CKR_MUTEX_BAD", "pkce"),
    ERROR_IO_PKCS11_CKR_MUTEX_NOT_LOCKED => ErrorInfo("ERROR_IO_PKCS11_CKR_MUTEX_NOT_LOCKED", "A PKCS#11 (Cryptoki) library function failed with return value CKR_MUTEX_NOT_LOCKED", "pkce"),
    ERROR_IO_PKCS11_CKR_NEW_PIN_MODE => ErrorInfo("ERROR_IO_PKCS11_CKR_NEW_PIN_MODE", "A PKCS#11 (Cryptoki) library function failed with return value CKR_NEW_PIN_MODE", "pkce"),
    ERROR_IO_PKCS11_CKR_NEXT_OTP => ErrorInfo("ERROR_IO_PKCS11_CKR_NEXT_OTP", "A PKCS#11 (Cryptoki) library function failed with return value CKR_NEXT_OTP", "pkce"),
    ERROR_IO_PKCS11_CKR_EXCEEDED_MAX_ITERATIONS => ErrorInfo("ERROR_IO_PKCS11_CKR_EXCEEDED_MAX_ITERATIONS", "A PKCS#11 (Cryptoki) library function failed with return value CKR_EXCEEDED_MAX_ITERATIONS", "pkce"),
    ERROR_IO_PKCS11_CKR_FIPS_SELF_TEST_FAILED => ErrorInfo("ERROR_IO_PKCS11_CKR_FIPS_SELF_TEST_FAILED", "A PKCS#11 (Cryptoki) library function failed with return value CKR_FIPS_SELF_TEST_FAILED", "pkce"),
    ERROR_IO_PKCS11_CKR_LIBRARY_LOAD_FAILED => ErrorInfo("ERROR_IO_PKCS11_CKR_LIBRARY_LOAD_FAILED", "A PKCS#11 (Cryptoki) library function failed with return value CKR_LIBRARY_LOAD_FAILED", "pkce"),
    ERROR_IO_PKCS11_CKR_PIN_TOO_WEAK => ErrorInfo("ERROR_IO_PKCS11_CKR_PIN_TOO_WEAK", "A PKCS#11 (Cryptoki) library function failed with return value CKR_PIN_TOO_WEAK", "pkce"),
    ERROR_IO_PKCS11_CKR_PUBLIC_KEY_INVALID => ErrorInfo("ERROR_IO_PKCS11_CKR_PUBLIC_KEY_INVALID", "A PKCS#11 (Cryptoki) library function failed with return value CKR_PUBLIC_KEY_INVALID", "pkce"),
    ERROR_IO_PKCS11_CKR_FUNCTION_REJECTED => ErrorInfo("ERROR_IO_PKCS11_CKR_FUNCTION_REJECTED", "A PKCS#11 (Cryptoki) library function failed with return value CKR_FUNCTION_REJECTED", "pkce"),
    ERROR_IO_PKCS11_ENCODING_ERROR => ErrorInfo("ERROR_IO_PKCS11_ENCODING_ERROR", "A PKCS#11 (Cryptoki) library function was unable to ASN.1 (DER) encode a data structure. See log for more details.", "pkce"),
    ERROR_IO_TLS_ERROR_DEFAULT_TRUST_STORE_NOT_FOUND => ErrorInfo("ERROR_IO_TLS_ERROR_DEFAULT_TRUST_STORE_NOT_FOUND", "Default TLS trust store not found on this system. Trusted CA certificates must be installed, or \"override default trust store\" must be used while creating the TLS context.", "io"),
    ERROR_IO_STREAM_SEEK_UNSUPPORTED => ErrorInfo("ERROR_IO_STREAM_SEEK_UNSUPPORTED", "Seek is not supported in the underlying I/O source.", "io"),
    ERROR_IO_TLS_ERROR_READ_FAILURE => ErrorInfo("ERROR_IO_TLS_ERROR_READ_FAILURE", "Failure during TLS read.", "io"),
    ERROR_IO_PEM_MALFORMED => ErrorInfo("ERROR_IO_PEM_MALFORMED", "Malformed PEM object encountered.", "io"),
    ERROR_IO_SOCKET_MISSING_EVENT_LOOP => ErrorInfo("ERROR_IO_SOCKET_MISSING_EVENT_LOOP", "Socket is missing its event loop.", "io"),
    ERROR_IO_TLS_UNKNOWN_ROOT_CERTIFICATE => ErrorInfo("ERROR_IO_TLS_UNKNOWN_ROOT_CERTIFICATE", "Channel shutdown due to tls unknown root certificate.", "io"),
    ERROR_IO_TLS_NO_ROOT_CERTIFICATE_FOUND => ErrorInfo("ERROR_IO_TLS_NO_ROOT_CERTIFICATE_FOUND", "Channel shutdown due to tls no root certificate found.", "io"),
    ERROR_IO_TLS_CERTIFICATE_EXPIRED => ErrorInfo("ERROR_IO_TLS_CERTIFICATE_EXPIRED", "Channel shutdown due to tls certificate expired.", "io"),
    ERROR_IO_TLS_CERTIFICATE_NOT_YET_VALID => ErrorInfo("ERROR_IO_TLS_CERTIFICATE_NOT_YET_VALID", "Channel shutdown due to tls certificate not yet valid.", "io"),
    ERROR_IO_TLS_BAD_CERTIFICATE => ErrorInfo("ERROR_IO_TLS_BAD_CERTIFICATE", "Channel shutdown due to tls certificate is malformed or not correctly formatted.", "io"),
    ERROR_IO_TLS_PEER_CERTIFICATE_EXPIRED => ErrorInfo("ERROR_IO_TLS_PEER_CERTIFICATE_EXPIRED", "Channel shutdown due to peer tls certificate is malformed or not correctly formatted.", "io"),
    ERROR_IO_TLS_BAD_PEER_CERTIFICATE => ErrorInfo("ERROR_IO_TLS_BAD_PEER_CERTIFICATE", "Channel shutdown due to peer tls certificate is malformed or not correctly formatted.", "io"),
    ERROR_IO_TLS_PEER_CERTIFICATE_REVOKED => ErrorInfo("ERROR_IO_TLS_PEER_CERTIFICATE_REVOKED", "Channel shutdown due to peer tls certificate has been revoked.", "io"),
    ERROR_IO_TLS_PEER_CERTIFICATE_UNKNOWN => ErrorInfo("ERROR_IO_TLS_PEER_CERTIFICATE_UNKNOWN", "Channel shutdown due to peer tls certificate is unknown.", "io"),
    ERROR_IO_TLS_INTERNAL_ERROR => ErrorInfo("ERROR_IO_TLS_INTERNAL_ERROR", "Channel shutdown due to internal SSL error.", "io"),
    ERROR_IO_TLS_CLOSED_GRACEFUL => ErrorInfo("ERROR_IO_TLS_CLOSED_GRACEFUL", "Channel shutdown due to connection closed gracefully.", "io"),
    ERROR_IO_TLS_CLOSED_ABORT => ErrorInfo("ERROR_IO_TLS_CLOSED_ABORT", "Channel shutdown due to connection closed due to an error.", "io"),
    ERROR_IO_TLS_INVALID_CERTIFICATE_CHAIN => ErrorInfo("ERROR_IO_TLS_INVALID_CERTIFICATE_CHAIN", "Channel shutdown due to invalid certificate chain.", "io"),
    ERROR_IO_TLS_HOST_NAME_MISMATCH => ErrorInfo("ERROR_IO_TLS_HOST_NAME_MISMATCH", "Channel shutdown due to certificate's host name does not match the endpoint host name.", "io"),
    ERROR_IO_DNS_QUERY_AGAIN => ErrorInfo("ERROR_IO_DNS_QUERY_AGAIN", "A temporary failure in name resolution occurred, please try again.", "io"),
)
const _unknown_error_str = "Unknown Error Code"


const _error_lock = ReentrantLock()
const _last_error = Dict{UInt64, Int}()

@inline function _error_thread_key()
    return UInt64(Base.Threads.threadid())
end

function last_error()
    key = _error_thread_key()
    lock(_error_lock)
    try
        return get(_last_error, key, 0)
    finally
        unlock(_error_lock)
    end
end

function _set_last_error(err::Int)
    key = _error_thread_key()
    lock(_error_lock)
    try
        if err == 0
            delete!(_last_error, key)
        else
            _last_error[key] = err
        end
    finally
        unlock(_error_lock)
    end
    return nothing
end

function error_str(err::Int)
    info = get(_error_registry, err, nothing)
    return info === nothing ? _unknown_error_str : info.error_str
end

function error_name(err::Int)
    info = get(_error_registry, err, nothing)
    return info === nothing ? _unknown_error_str : info.literal_name
end

# Helper for determining if an error code is retryable
function io_error_code_is_retryable(error_code::Integer)::Bool
    return error_code == ERROR_IO_SOCKET_CLOSED ||
        error_code == ERROR_IO_SOCKET_CONNECT_ABORTED ||
        error_code == ERROR_IO_SOCKET_CONNECTION_REFUSED ||
        error_code == ERROR_IO_SOCKET_NETWORK_DOWN ||
        error_code == ERROR_IO_DNS_QUERY_AGAIN ||
        error_code == ERROR_IO_DNS_NO_ADDRESS_FOR_HOST ||
        error_code == ERROR_IO_SOCKET_TIMEOUT ||
        error_code == ERROR_IO_TLS_NEGOTIATION_TIMEOUT
end

function io_error_code_is_tls(error_code::Integer)::Bool
    return error_code == ERROR_IO_TLS_ERROR_NEGOTIATION_FAILURE ||
        error_code == ERROR_IO_TLS_ERROR_NOT_NEGOTIATED ||
        error_code == ERROR_IO_TLS_ERROR_WRITE_FAILURE ||
        error_code == ERROR_IO_TLS_ERROR_ALERT_RECEIVED ||
        error_code == ERROR_IO_TLS_CTX_ERROR ||
        error_code == ERROR_IO_TLS_VERSION_UNSUPPORTED ||
        error_code == ERROR_IO_TLS_CIPHER_PREF_UNSUPPORTED ||
        error_code == ERROR_IO_TLS_NEGOTIATION_TIMEOUT ||
        error_code == ERROR_IO_TLS_ALERT_NOT_GRACEFUL ||
        error_code == ERROR_IO_TLS_DIGEST_ALGORITHM_UNSUPPORTED ||
        error_code == ERROR_IO_TLS_SIGNATURE_ALGORITHM_UNSUPPORTED ||
        error_code == ERROR_IO_TLS_ERROR_READ_FAILURE ||
        error_code == ERROR_IO_TLS_UNKNOWN_ROOT_CERTIFICATE ||
        error_code == ERROR_IO_TLS_NO_ROOT_CERTIFICATE_FOUND ||
        error_code == ERROR_IO_TLS_CERTIFICATE_EXPIRED ||
        error_code == ERROR_IO_TLS_CERTIFICATE_NOT_YET_VALID ||
        error_code == ERROR_IO_TLS_BAD_CERTIFICATE ||
        error_code == ERROR_IO_TLS_PEER_CERTIFICATE_EXPIRED ||
        error_code == ERROR_IO_TLS_BAD_PEER_CERTIFICATE ||
        error_code == ERROR_IO_TLS_PEER_CERTIFICATE_REVOKED ||
        error_code == ERROR_IO_TLS_PEER_CERTIFICATE_UNKNOWN ||
        error_code == ERROR_IO_TLS_INTERNAL_ERROR ||
        error_code == ERROR_IO_TLS_CLOSED_GRACEFUL ||
        error_code == ERROR_IO_TLS_CLOSED_ABORT ||
        error_code == ERROR_IO_TLS_INVALID_CERTIFICATE_CHAIN ||
        error_code == ERROR_IO_TLS_HOST_NAME_MISMATCH
end

function raise_error_private(err::Int)
    _set_last_error(err)
    return nothing
end

function raise_error(err::Int)
    raise_error_private(err)
    return OP_ERR
end

function translate_and_raise_io_error_or(error_no::Integer, fallback_error_code::Integer)
    error_no_i = Int(error_no)
    fallback_i = Int(fallback_error_code)
    if error_no_i == Libc.EINVAL
        if fallback_i != ERROR_SYS_CALL_FAILURE
            return raise_error(fallback_i)
        else
            return raise_error(ERROR_INVALID_ARGUMENT)
        end
    elseif error_no_i == Libc.EPERM || error_no_i == Libc.EACCES
        return raise_error(ERROR_NO_PERMISSION)
    elseif error_no_i == Libc.EISDIR || error_no_i == Libc.ENAMETOOLONG || error_no_i == Libc.ENOENT || error_no_i == Libc.ENOTDIR
        return raise_error(ERROR_FILE_INVALID_PATH)
    elseif error_no_i == Libc.EMFILE || error_no_i == Libc.ENFILE
        return raise_error(ERROR_MAX_FDS_EXCEEDED)
    elseif error_no_i == Libc.ENOMEM
        return raise_error(ERROR_OOM)
    elseif error_no_i == Libc.ENOSPC
        return raise_error(ERROR_NO_SPACE)
    elseif error_no_i == Libc.ENOTEMPTY
        return raise_error(ERROR_DIRECTORY_NOT_EMPTY)
    else
        return raise_error(fallback_i)
    end
end

function translate_and_raise_io_error(error_no::Integer)
    return translate_and_raise_io_error_or(error_no, ERROR_SYS_CALL_FAILURE)
end
