@enumx LogLevel::UInt8 begin
    NONE = 0
    FATAL = 1
    ERROR = 2
    WARN = 3
    INFO = 4
    DEBUG = 5
    TRACE = 6
end

const LOG_LEVEL_NONE = LogLevel.NONE
const LOG_LEVEL_FATAL = LogLevel.FATAL
const LOG_LEVEL_ERROR = LogLevel.ERROR
const LOG_LEVEL_WARN = LogLevel.WARN
const LOG_LEVEL_INFO = LogLevel.INFO
const LOG_LEVEL_DEBUG = LogLevel.DEBUG
const LOG_LEVEL_TRACE = LogLevel.TRACE

const LL_NONE = LOG_LEVEL_NONE
const LL_FATAL = LOG_LEVEL_FATAL
const LL_ERROR = LOG_LEVEL_ERROR
const LL_WARN = LOG_LEVEL_WARN
const LL_INFO = LOG_LEVEL_INFO
const LL_DEBUG = LOG_LEVEL_DEBUG
const LL_TRACE = LOG_LEVEL_TRACE
const LL_COUNT = 7

const LogSubject = UInt32

const LOG_SUBJECT_STRIDE_BITS = 10
const LOG_SUBJECT_STRIDE = UInt32(1) << LOG_SUBJECT_STRIDE_BITS

LOG_SUBJECT_BEGIN_RANGE(x) = LogSubject(x) * LOG_SUBJECT_STRIDE
LOG_SUBJECT_END_RANGE(x) = (LogSubject(x) + 1) * LOG_SUBJECT_STRIDE - 1

struct LogSubjectInfo
    subject_id::LogSubject
    subject_name::String
    subject_description::String
end

struct LogSubjectInfoList
    subject_list::Memory{LogSubjectInfo}
end

const LS_COMMON_GENERAL = LOG_SUBJECT_BEGIN_RANGE(COMMON_PACKAGE_ID)
const LS_COMMON_TASK_SCHEDULER = LS_COMMON_GENERAL + 1
const LS_COMMON_THREAD = LS_COMMON_GENERAL + 2
const LS_COMMON_MEMTRACE = LS_COMMON_GENERAL + 3
const LS_COMMON_XML_PARSER = LS_COMMON_GENERAL + 4
const LS_COMMON_IO = LS_COMMON_GENERAL + 5
const LS_COMMON_BUS = LS_COMMON_GENERAL + 6
const LS_COMMON_TEST = LS_COMMON_GENERAL + 7
const LS_COMMON_JSON_PARSER = LS_COMMON_GENERAL + 8
const LS_COMMON_CBOR = LS_COMMON_GENERAL + 9
const LS_COMMON_LAST = LOG_SUBJECT_END_RANGE(COMMON_PACKAGE_ID)
